'use strict';
// Space Arcade. Student responses stay in this browser unless exported by the learner.
const APP = 'blackgold-space-arcade', VERSION = 1, STORAGE_KEY = APP + '-v' + VERSION;
const $ = id => document.getElementById(id);
const escapeHTML = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const READINGS = {
  A: {title:'How telescopes help us', text:'A telescope gathers light from distant objects. Its lenses or mirrors focus that light to make an image. Larger lenses or mirrors can collect more light, helping astronomers observe faint objects.\n\nPeople can use a telescope to study details that their eyes alone cannot easily see. Choosing a viewing tool depends on what you want to observe.', website:'NASA Space Place', format:'article', original:'How Do Telescopes Work?', url:'https://spaceplace.nasa.gov/telescopes/en/'},
  B: {title:'Finding a place to skywatch', text:'You can begin skywatching with your eyes. Binoculars and telescopes reveal finer details.\n\nLight from streets and buildings can scatter into the night sky. This glow makes faint stars harder to see. A darker, safe viewing place can help.', website:'NASA Science', format:'questions and answers', original:'Skywatching FAQ', url:'https://science.nasa.gov/skywatching/faq/'}
};
const CATEGORIES = [
  {id:'noun', label:'Noun', desc:'Names a person, place or thing.', words:['stars','sky']},
  {id:'pronoun', label:'Pronoun', desc:'Takes the place of a noun.', words:['We','they']},
  {id:'verb', label:'Verb', desc:'Shows an action or a state of being.', words:['observe','shine']},
  {id:'adjective', label:'Adjective', desc:'Describes a noun.', words:['bright']},
  {id:'adverb', label:'Adverb', desc:'Here, tells how an action happens.', words:['carefully']},
  {id:'preposition', label:'Preposition', desc:'Shows a relationship, such as place.', words:['in']},
  {id:'conjunction', label:'Conjunction', desc:'Joins words or parts of a sentence.', words:['and']},
  {id:'interjection', label:'Interjection', desc:'Expresses a sudden feeling.', words:['Wow']}
];
const ACTIVITIES = [
 {id:'read', short:'Read & explore', title:'Tools and the night sky', type:'Reading room', tone:'blue', icon:'telescope', description:'Two short readings. Big ideas to explore.', lead:'Start with the classroom passages, or return here whenever an activity asks for evidence.', fields:[], teacher:{goal:'Build shared knowledge about viewing tools and observing conditions.', steps:['Read both passages aloud or with a partner. Ask students to point to the detail behind an idea.','Separate the classroom adaptations from the original NASA pages. The source cards identify the originals.','Use a safe observing location with adult supervision. This app is a reading and thinking activity; it does not require a night trip.'], model:'A telescope gathers and focuses light. A darker, safe location can make faint stars easier to see because light from streets and buildings can brighten the sky.'}},
 {id:'kwl', short:'Wonder wall', title:'Know, wonder, learn', type:'Move your ideas', tone:'yellow', icon:'notes', description:'Add sticky notes. Move ideas as you learn.', lead:'How do objects in space impact daily life? Add what you think and wonder. After reading, add what you learned and revisit an idea.', fields:[
  {key:'know',label:'Know',prompt:'What do I already know?',starter:'I think…'},
  {key:'wonder',label:'Wonder',prompt:'What am I curious about?',starter:'I wonder…'},
  {key:'learn',label:'Learn',prompt:'What did I learn? Include your evidence.',starter:'I learned… My evidence is…'},
  {key:'revisit',label:'Revisit an idea',prompt:'What did the evidence confirm or change?',starter:'At first I thought… Now I think…',full:true}
 ],check:'A Know idea is a starting thought, not automatically a fact. In Learn, name the passage detail that supports the new idea.', teacher:{goal:'Make prior knowledge visible and revisit it using evidence.',steps:['Before reading, add one Know note and one Wonder question. Students can also type longer responses.','After reading, add a Learn note. Move a question to Learn when students can answer it, or keep it in Wonder for future inquiry.','Ask: What evidence changed your thinking? The broad daily-life inquiry can continue beyond these two passages.'],model:'Know: I think telescopes help us see far away. Wonder: Why can we see more stars at some places? Learn: Street and building lights can brighten the sky and hide faint stars. Revisit: I first thought a darker park had more stars; now I think more of the existing stars are visible.',note:'This board is open-ended. Notes are not marked right or wrong.'}},
 {id:'infer', short:'Evidence detective', title:'Why can we see more stars?', type:'Sort & infer', tone:'mint', icon:'magnifier', description:'Separate evidence, knowledge, and inference.', lead:'Two groups observe on the same clear night. The group at a dark park records more stars. Sort the clues, then explain what you can infer.', fields:[
  {key:'text',label:'The text says',prompt:'Write a useful detail from Reading B.',starter:'The text says…'},
  {key:'know',label:'I already know',prompt:'What helpful idea do you bring to this observation?',starter:'I know…'},
  {key:'infer',label:'I can infer',prompt:'Combine the reading detail and your knowledge.',starter:'I infer… because…'}
 ],check:'Explain why more stars were visible. Use a detail from Reading B and a helpful idea you already know.',teacher:{goal:'Distinguish passage evidence, prior knowledge, and an inference.',steps:['Model the difference between something the passage states and an idea students bring to it.','Have partners sort the six cards, then use the feedback to revise.','Ask students to connect text evidence and prior knowledge in the written inference.'],model:'The text says glow from lights makes faint stars harder to see. I know light can make dim objects difficult to notice. I infer the darker park let the group see more stars because less sky glow hid the faint ones.',note:'The park does not create new stars. The observation is about visibility, not a change in the number of stars in space.'}},
 {id:'pros', short:'Skywatching choices', title:'A place for skywatching', type:'Sort & decide', tone:'coral', icon:'balance', description:'Weigh the park’s benefits and challenges.', lead:'A class can use its lit schoolyard or travel 30 minutes to a darker park. Both are safe. The trip needs transport. Compare the options, then choose a place.',fields:[
  {key:'advantages',label:'Advantages',prompt:'How could the darker park help? Use Reading B.',starter:'The park could help us…'},
  {key:'challenges',label:'Challenges',prompt:'What could make the trip difficult? Use the scenario.',starter:'The trip could make it harder to…'},
  {key:'decision',label:'My decision',prompt:'Which place would you choose, and why?',starter:'I would choose… because…'}
 ],check:'Consider both the viewing conditions and the practical needs of the class. Explain your choice with evidence.',teacher:{goal:'Use evidence and practical constraints to justify a decision.',steps:['Sort the cards relative to the darker-park trip. “True of both” separates a shared condition from a unique advantage.','Invite different decisions. The sort has evidence-based categories; the final choice depends on priorities.','Ask: Which challenge could the class plan for? What would make the schoolyard a reasonable choice?'],model:'The park could make faint stars easier to see, but the class needs transport and travel time. I would choose the park if we can arrange transport because our goal is observing faint stars.',note:'A well-supported schoolyard choice can also be reasonable. Do not grade the destination itself.'}},
 {id:'problem',short:'Mission planner',title:'A brighter sky, fewer stars',type:'Build a plan',tone:'blue',icon:'light',description:'Connect a problem, a solution, and a fair test.',lead:'Nearby floodlights point upward. A class wants to see faint stars while keeping walkways safely lit. Build an evidence-based plan, then describe your own solution.',fields:[
  {key:'problem',label:'The problem',prompt:'What is getting in the way? Use Reading B as evidence.',starter:'Our problem is…'},
  {key:'solution',label:'A possible solution',prompt:'What could the class propose? Include safe lighting for people.',starter:'Our plan is… It could help because…'},
  {key:'test',label:'Test the plan',prompt:'What would you observe before and after the change?',starter:'I would compare… I would keep… the same.'}
 ],check:'Keep safe walkway lighting in your plan. Compare observations under similar sky conditions, using the same place and observing method.',teacher:{goal:'Connect a proposed solution to evidence and plan a fair comparison.',steps:['Students sort cards into problem evidence, a possible solution, and a test plan.','Discuss what stays the same: location, observing method, time spent observing, and similar sky conditions.','Treat the proposed lighting change as a class recommendation for an adult to evaluate. Students do not alter outdoor lighting.'],model:'Our problem is that upward light can brighten the sky and hide faint stars. We could ask an adult to review shielding or aiming lights downward while keeping walkways lit. I would compare the same area of sky before and after, from the same place, using the same observing method under similar conditions.',note:'This is a proposed investigation. The app does not simulate star counts or claim measured results.'}},
 {id:'acaps',short:'Source explorer',title:'Who made this source?',type:'ACAPS clues',tone:'purple',icon:'source',description:'Match source clues, then explain your thinking.',lead:'Use Reading A and its source card. Move each clue to the source question it helps answer, then write your response with evidence. You can also explore the original article.',fields:[
  {key:'author',label:'A · Author',prompt:'Who created the original source?',starter:'My response and evidence…'},
  {key:'context',label:'C · Context',prompt:'On which website does it appear? What kind of text is it?',starter:'My response and evidence…'},
  {key:'audience',label:'A · Audience',prompt:'Who might use this information? What is your clue?',starter:'My response and evidence…'},
  {key:'purpose',label:'P · Purpose',prompt:'What does it help readers understand?',starter:'My response and evidence…'},
  {key:'significance',label:'S · Significance',prompt:'How does it help our space inquiry?',starter:'My response and evidence…'}
 ],source:'A',check:'For audience and purpose, explain which details support your idea. The publisher and website are given in the source card.',teacher:{goal:'Identify source metadata and explain possible audience, purpose, and significance.',steps:['Read the publisher, website, and format on Reading A’s source card.','The clue match models one useful connection. Real evidence can support more than one source question.','Distinguish an identified publisher from an individual author. The source card gives NASA, not a named writer.'],model:'Author: NASA is the publisher. Context: the original is an article on NASA Space Place. Audience: learners interested in telescopes; the classroom passage explains basic ideas. Purpose: explain how telescopes gather and focus light. Significance: it helps us understand how people choose tools to observe space.',note:'Audience and purpose are interpretations supported by details. More than one defensible response is possible.'}},
 {id:'soap',short:'Source voice',title:'The voice of a source',type:'SOAPSTone clues',tone:'mint',icon:'speech',description:'Explore the voice and purpose of Reading B.',lead:'Use Reading B and its source card. Match the clues, then think about the information, the reader, and the way this classroom passage is written.',fields:[
  {key:'speaker',label:'Speaker',prompt:'Whose original information is this passage based on?',starter:'My response and evidence…'},
  {key:'occasion',label:'Occasion',prompt:'What skywatching need or question does it address?',starter:'My response and evidence…'},
  {key:'audience',label:'Audience',prompt:'Who might find this information useful?',starter:'My response and evidence…'},
  {key:'purpose',label:'Purpose',prompt:'What can readers learn or do?',starter:'My response and evidence…'},
  {key:'subject',label:'Subject',prompt:'What is the main topic?',starter:'My response and evidence…'},
  {key:'tone',label:'Tone',prompt:'How does the reading sound? Give a text clue.',starter:'My response and evidence…'}
 ],source:'B',check:'Tone can be shown through explanations and suggestions. Use an actual phrase from the classroom passage to support your idea.',teacher:{goal:'Describe source voice and distinguish facts from supported interpretations.',steps:['Use the source card for Speaker. Use passage details for the other questions.','Explain that these passages are classroom adaptations, not quotations of the full NASA originals.','For Tone, accept a sensible description supported by language in Reading B.'],model:'Speaker: based on NASA information. Occasion: a reader needs advice about where and how to skywatch. Audience: beginning skywatchers. Purpose: help people choose viewing tools and a location. Subject: tools and conditions for seeing the night sky. Tone: helpful and explanatory; “A darker, safe viewing place can help” offers advice.',note:'The tone analysis describes the classroom adaptation. Opening the original FAQ is optional.'}},
 {id:'language',short:'Space word sort',title:'Space words at work',type:'Parts of speech',tone:'yellow',icon:'words',description:'Move word tiles into eight language categories.',lead:'Find at least one example of each part of speech in the sentence. You can sort all the word tiles, then explain one word’s job.',fields:[{key:'explain',label:'Explain a word’s job',prompt:'Choose one word. What does it do in this sentence?',starter:'The word… is a… because…',full:true}],check:'Use the job each word does in this sentence. Some categories have more than one example.',teacher:{goal:'Identify the eight traditional parts of speech in context.',steps:['Read the sentence aloud. Have students move one word into each category before checking.','Students can continue sorting all 11 tiles. Some categories accept more than one correct word.','Ask students to explain a word’s function, such as carefully describing how we observe.'],model:'Noun: stars or sky. Pronoun: We or they. Verb: observe or shine. Adjective: bright. Adverb: carefully. Preposition: in. Conjunction: and. Interjection: Wow.',note:'“The” is a determiner, outside these eight categories, so it is not a movable tile.'}}
];
const BOARDS = {
 infer: {zones:[{id:'text',label:'The text says',desc:'A detail stated in Reading B.'},{id:'knowledge',label:'I already know',desc:'A helpful idea brought to the reading.'},{id:'inference',label:'I can infer',desc:'An explanation built from clues.'},{id:'check',label:'Needs checking',desc:'A claim the evidence does not support.'}], cards:[
  {id:'glow',text:'Glow from street and building lights makes faint stars harder to see.',zone:'text',reason:'Reading B states this directly.'},
  {id:'dim',text:'I know a dim object can be hard to notice beside a bright light.',zone:'knowledge',reason:'This is a helpful everyday idea brought to the reading.'},
  {id:'visible',text:'The park group probably saw more stars because less sky glow hid the faint ones.',zone:'inference',reason:'This combines the observation with the reading’s detail about sky glow.'},
  {id:'dark',text:'A darker, safe viewing place can help.',zone:'text',reason:'This is stated in Reading B.'},
  {id:'eyes',text:'I know my eyes need to detect light for me to see something.',zone:'knowledge',reason:'This is prior knowledge, not a statement in Reading B.'},
  {id:'newstars',text:'The dark park made new stars appear in space.',zone:'check',reason:'Seeing more stars does not mean new stars were created.'}
 ]},
 pros: {zones:[{id:'advantages',label:'Park advantages',desc:'What helps the viewing goal?'},{id:'challenges',label:'Trip challenges',desc:'What needs planning?'},{id:'both',label:'True of both',desc:'A condition shared by both locations.'}],cards:[
  {id:'faint',text:'A darker sky can make faint stars easier to see.',zone:'advantages',reason:'Reading B supports the darker park’s viewing advantage.'},
  {id:'glow',text:'Less sky glow can help the class notice more stars.',zone:'advantages',reason:'Less sky glow helps the observing goal.'},
  {id:'time',text:'The class has a 30-minute trip to the park.',zone:'challenges',reason:'Travel time is a practical need to plan for.'},
  {id:'transport',text:'The class needs transport for the park trip.',zone:'challenges',reason:'The scenario identifies transport as a trip requirement.'},
  {id:'safe',text:'Both the schoolyard and the park are safe.',zone:'both',reason:'The scenario explicitly says both are safe.'}
 ]},
 problem:{zones:[{id:'problem',label:'Problem evidence',desc:'What is getting in the way?'},{id:'solution',label:'Possible solution',desc:'A proposal that keeps people safe.'},{id:'test',label:'Fair comparison',desc:'A plan for observing before and after.'}],cards:[
  {id:'up',text:'Nearby floodlights point upward.',zone:'problem',reason:'The scenario identifies upward-pointing lights.'},
  {id:'glow',text:'Light can brighten the sky and make faint stars harder to see.',zone:'problem',reason:'Reading B explains how sky glow affects visibility.'},
  {id:'shield',text:'Ask an adult to review shields or downward aiming for the lights.',zone:'solution',reason:'This proposes reducing upward light. An adult would evaluate the change.'},
  {id:'walkways',text:'Keep enough light on walkways for people to move safely.',zone:'solution',reason:'Safe walkway lighting is a requirement of the plan.'},
  {id:'count',text:'Compare stars visible in the same area of sky before and after.',zone:'test',reason:'This gives an observation to compare.'},
  {id:'same',text:'Use the same place, tool, and observing time under similar sky conditions.',zone:'test',reason:'Keeping observing conditions similar makes the comparison more useful.'}
 ]},
 acaps:{zones:[],cards:[
  {id:'publisher',text:'Publisher: NASA.',zone:'author',reason:'The source card identifies NASA as publisher of the original.'},
  {id:'website',text:'Website: NASA Space Place. Format: article.',zone:'context',reason:'Website and format describe the original’s context.'},
  {id:'learners',text:'Possible readers: learners curious about how telescopes work.',zone:'audience',reason:'The basic explanations support this possible audience.'},
  {id:'explain',text:'It explains how lenses or mirrors gather and focus light.',zone:'purpose',reason:'This describes what the passage helps readers understand.'},
  {id:'inquiry',text:'It helps us think about choosing tools to observe space.',zone:'significance',reason:'This connects the reading to our space inquiry.'}
 ],guided:true},
 soap:{zones:[],cards:[
  {id:'nasa',text:'The original information comes from NASA.',zone:'speaker',reason:'The source card identifies the original publisher.'},
  {id:'need',text:'A skywatcher needs help choosing a viewing tool or place.',zone:'occasion',reason:'This describes the need addressed by the reading.'},
  {id:'beginners',text:'Possible readers: people beginning to skywatch.',zone:'audience',reason:'The simple suggestions support this possible audience.'},
  {id:'choose',text:'It helps readers choose tools and safer, darker viewing places.',zone:'purpose',reason:'This describes what readers can learn or do.'},
  {id:'topic',text:'The main topic is tools and conditions for skywatching.',zone:'subject',reason:'This names the passage’s main topic.'},
  {id:'voice',text:'“A darker, safe viewing place can help” sounds helpful and explanatory.',zone:'tone',reason:'This uses a phrase from the classroom passage to describe its tone.'}
 ],guided:true},
 language:{zones:CATEGORIES.map(c=>({id:c.id,label:c.label,desc:c.desc})),cards:['Wow','We','carefully','observe','bright','stars','in','sky','and','they','shine'].map((word,i)=>({id:'word-'+i,text:word,zone:CATEGORIES.find(c=>c.words.includes(word)).id,reason:''}))}
};
for(const id of ['acaps','soap']) BOARDS[id].zones = ACTIVITIES.find(a=>a.id===id).fields.map(f=>({id:f.key,label:f.label,desc:f.prompt}));
const KWL_ZONES = [{id:'know',label:'Know',desc:'A starting idea: I think…'},{id:'wonder',label:'Wonder',desc:'A question: I wonder…'},{id:'learn',label:'Learn',desc:'A new idea with evidence: I learned…'}];
const allowedFields = Object.fromEntries(ACTIVITIES.map(a=>[a.id,new Set(a.fields.map(f=>f.key))]));
let state = freshState(), teacher = false, selected = null, checked = new Set(), saveTimer, storageAvailable = true, pendingAction = null, drag = null, suppressClick = false;
function freshState(){return {app:APP,version:VERSION,active:'home',responses:{},placements:{},notes:[]};}
function validateState(data){
 if(!data || data.app!==APP || data.version!==VERSION || typeof data.responses!=='object' || !data.responses || Array.isArray(data.responses)) throw new Error('Choose a Space Arcade work file saved by this app.');
 const out=freshState();out.active=['home',...ACTIVITIES.map(a=>a.id)].includes(data.active)?data.active:'home';
 for(const a of ACTIVITIES){out.responses[a.id]={};for(const f of a.fields){const value=data.responses[a.id]?.[f.key];if(typeof value==='string')out.responses[a.id][f.key]=value.slice(0,12000);}}
 for(const [id,board]of Object.entries(BOARDS)){out.placements[id]={};for(const card of board.cards){const zone=data.placements?.[id]?.[card.id];if(board.zones.some(z=>z.id===zone))out.placements[id][card.id]=zone;}}
 if(Array.isArray(data.notes)){const seen=new Set();for(const note of data.notes.slice(0,60)){if(!note || typeof note.id!=='string' || !/^note-[a-z0-9-]+$/.test(note.id) || seen.has(note.id) || typeof note.text!=='string' || !KWL_ZONES.some(z=>z.id===note.zone))continue;seen.add(note.id);out.notes.push({id:note.id,text:note.text.slice(0,500),zone:note.zone});}}
 return out;
}
function initStorage(){try{const saved=localStorage.getItem(STORAGE_KEY);if(saved)state=validateState(JSON.parse(saved));localStorage.setItem(STORAGE_KEY,JSON.stringify(state));}catch(error){storageAvailable=false;}updateSaveStatus();}
function updateSaveStatus(){ $('save-status').textContent=storageAvailable?'Saved in this browser · Save work to keep a copy.':'Browser saving unavailable · Use Save work before leaving.';}
function save(){clearTimeout(saveTimer);try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state));storageAvailable=true;}catch(error){storageAvailable=false;}updateSaveStatus();}
function scheduleSave(){clearTimeout(saveTimer);$('save-status').textContent=storageAvailable?'Saving your ideas…':'Browser saving unavailable · Use Save work before leaving.';saveTimer=setTimeout(save,300);}
function announce(text){$('announcement').textContent='';requestAnimationFrame(()=>{$('announcement').textContent=text;});}
function icon(name,large=false){
 const drawings={
  telescope:'<path d="m25 41 48-25 11 21-48 25Z" fill="#91c9f3"/><path d="m72 16 7-4 12 22-7 3" fill="#fffaf2"/><path d="m23 42-7 4 9 17 10-6" fill="#ffcb4f"/><path d="m54 48-9 30m9-30 20 30m-20-30 5 30"/><circle cx="52" cy="49" r="5" fill="#ff837b"/><path d="m94 7 2 5 5 2-5 2-2 5-2-5-5-2 5-2Z" fill="#ffcb4f"/>',
  notes:'<path d="M19 18h42v45H19Z" fill="#fffaf2" transform="rotate(-8 40 40)"/><path d="M53 27h39v44H53Z" fill="#92d8b8" transform="rotate(7 73 49)"/><path d="m27 31 23-3m-21 12 23-3m12 8 20 2m-21 8 20 2"/><path d="m12 6 2 5 5 2-5 2-2 5-2-5-5-2 5-2Z" fill="#ffcb4f"/>',
  magnifier:'<circle cx="47" cy="35" r="24" fill="#fffaf2"/><circle cx="47" cy="35" r="17" fill="#91c9f3"/><path d="m65 53 24 24 8-8-24-24Z" fill="#ff837b"/><path d="m41 26 3 6 7 1-5 5 1 7-6-3-6 3 1-7-5-5 7-1Z" fill="#ffcb4f"/>',
  balance:'<path d="M56 12v58M23 26h66M44 71h25"/><path d="m23 26-14 28h28Zm66 0L75 54h28Z" fill="#fffaf2"/><path d="M9 54q14 18 28 0m38 0q14 18 28 0" fill="#91c9f3"/><circle cx="56" cy="25" r="6" fill="#ffcb4f"/><path d="m56 7 4 6-4 6-4-6Z" fill="#ffcb4f"/>',
  light:'<path d="M36 35q0-24 23-24t23 24q0 12-12 21v10H48V56Q36 46 36 35Z" fill="#ffcb4f"/><path d="M48 66h22v9H48Zm4 9h14v5H52Z" fill="#fffaf2"/><path d="m51 35 8 12 8-12M59 47v18M26 28l-9-3m73 3 9-3M32 8l-6-8m60 8 6-8"/>',
  source:'<path d="M30 8h43l16 17v52H30Z" fill="#fffaf2"/><path d="M73 8v17h16" fill="#91c9f3"/><path d="M42 35h35M42 45h25M42 55h29"/><circle cx="29" cy="58" r="15" fill="#ffcb4f"/><path d="m22 58 5 5 10-11"/>',
  speech:'<path d="M15 16h68v42H47L32 73V58H15Z" fill="#fffaf2"/><path d="M63 41h34v30H83L73 81V71H63Z" fill="#cdb0ea"/><path d="M27 30h42M27 40h29m18 12h13m-13 8h13"/>',
  words:'<path d="M15 15h31v36H15Z" fill="#fffaf2" transform="rotate(-9 30 33)"/><path d="M52 12h30v36H52Z" fill="#91c9f3" transform="rotate(7 67 30)"/><path d="M40 49h32v32H40Z" fill="#92d8b8"/><path d="m24 40 6-17 6 17m-10-5h8m33-14v18m-5-9h10m-24 29 6 11 7-11"/>',
  planet:'<circle cx="59" cy="43" r="27" fill="#91c9f3"/><path d="M34 34q17-8 34 7m-30 13q16-8 40 5"/><ellipse cx="59" cy="43" rx="51" ry="12" transform="rotate(-24 59 43)" fill="none"/><path d="m100 5 2 6 6 2-6 2-2 6-2-6-6-2 6-2Z" fill="#ffcb4f"/><circle cx="17" cy="69" r="3" fill="#ff837b"/>'
 };
 return `<svg ${large?'class="banner-art"':''} viewBox="0 0 115 88" aria-hidden="true" fill="none" stroke="#112739" stroke-width="2.3" stroke-linecap="round" stroke-linejoin="round">${drawings[name]||drawings.planet}</svg>`;
}
function progress(id){const a=ACTIVITIES.find(a=>a.id===id);let count=a.fields.filter(f=>(state.responses[id]?.[f.key]||'').trim()).length;count+=id==='kwl'?state.notes.length:Object.keys(state.placements[id]||{}).length;return count?'Ideas saved':'Ready to explore';}
function teacherIntro(){return `<aside class="teacher-banner"><strong>Teacher view</strong><p>Model responses and teaching notes appear with each activity. Use the sorts for practice and discuss the written reasoning. Save work creates a learner’s response file; Load work opens it in this browser.</p><a href="packet.pdf" target="_blank" rel="noopener">Original light-mode packet ↗</a></aside>`;}
function renderHome(){
 const html=`${teacher?teacherIntro():''}<section class="home-intro"><div><p class="eyebrow">Grade 4 science · Space</p><h1 id="page-heading" class="hero-title" tabindex="-1">LITTLE CLUES.<span>BIG UNIVERSE.</span></h1><p class="home-subtitle">Read it. Move it. Make sense of it.</p></div><div class="hero-art">${icon('planet')}<p class="hand-note">Your next discovery<br>starts with a question.</p></div></section><div class="inquiry"><strong>Our inquiry</strong><span>How do objects in space impact daily life?</span></div><p class="choose-label">CHOOSE YOUR ACTIVITY</p><div class="games">${ACTIVITIES.map((a,i)=>`<article class="game-card" style="--tone:var(--${a.tone})"><div class="game-top"><span class="game-number">${String(i+1).padStart(2,'0')}</span><span class="activity-type">${a.type}</span></div><div class="game-art">${icon(a.icon)}</div><h2>${a.short}</h2><p>${a.description}</p><button class="primary" data-go="${a.id}" aria-label="Start ${a.short}">Start exploring <span aria-hidden="true">→</span></button><span class="complete-note">${a.id==='read'?'2 classroom readings':progress(a.id)}</span></article>`).join('')}</div><p class="privacy-note">Your ideas stay in this browser. No accounts or student uploads. Use Save work to keep a copy or share a response file with your teacher. On shared devices, use New learner after saving.</p>${teacher?`<details class="teacher-notes"><summary>Suggested teaching sequence</summary><p>Begin with Know and Wonder. Read the passages together, then use Evidence detective, Skywatching choices, and Mission planner. Return to Learn and Revisit an idea. ACAPS, SOAPSTone, and the word sort can be small-group language activities.</p><p>The sorts provide feedback on the supplied practice cards. Open-ended writing and the Wonder wall need teacher discussion. There is no automatic writing grade.</p><p>For younger readers, model one category at a time and let partners explain aloud before typing. For extension, compare the classroom adaptation with the linked original NASA page.</p></details>`:''}`;
 $('main').innerHTML=html;
}
function readingMarkup(keys=['A','B']){return `<div class="readings">${keys.map(key=>{const r=READINGS[key];return `<article class="reading"><p class="eyebrow">Reading ${key}</p><h2>${r.title}</h2><p>${escapeHTML(r.text)}</p><div class="source-card"><strong>Source card</strong><br>Publisher: NASA. Website: ${r.website}. Format: ${r.format}.<br><strong>Original source:</strong> ${r.original}.<br><a class="source-link" href="${r.url}" target="_blank" rel="noopener noreferrer">Explore the original NASA source ↗</a></div></article>`;}).join('')}</div><p class="small-note" style="margin-top:12px">Classroom passages adapted from NASA. They are simplified readings, not quotations of the original pages.</p>`;}
function safetyMarkup(){return '<aside class="safety"><h3>Skywatching reminder</h3><p>Observe with an adult and choose a safe location. Never look directly at the Sun or point binoculars or a telescope at it.</p></aside>';}
function fieldsMarkup(a){return `<section class="writing"><h2>Your thinking</h2><div class="${a.source?'source-fields':'writing-grid'}">${a.fields.map(f=>`<section class="field ${f.full?'full':''}"><div><label for="${a.id}-${f.key}">${f.label}</label><p id="hint-${a.id}-${f.key}">${f.prompt}</p></div><textarea id="${a.id}-${f.key}" data-activity="${a.id}" data-field="${f.key}" aria-describedby="hint-${a.id}-${f.key}" placeholder="${f.starter}" maxlength="12000">${escapeHTML(state.responses[a.id]?.[f.key]||'')}</textarea></section>`).join('')}</div></section>`;}
function boardFor(id){if(id==='kwl')return {zones:KWL_ZONES,cards:state.notes.map(n=>({...n,zone:n.zone}))};return BOARDS[id];}
function placement(id,card){return id==='kwl'?card.zone:state.placements[id]?.[card.id]||'bank';}
function cardMarkup(id,card){let cls='',mark='';if(checked.has(id)&&id!=='kwl'&&placement(id,card)!=='bank'){const correct=placement(id,card)===card.zone;cls=correct?'is-correct':'is-wrong';mark=`<span class="card-check">${correct?'✓':'↻'}</span>`;}return `<button type="button" class="move-card ${cls}" data-board="${id}" data-card="${card.id}" aria-pressed="${selected?.board===id&&selected?.card===card.id}" aria-label="${escapeHTML(card.text)}. Select to move."><span class="grip" aria-hidden="true">⠿</span><span>${escapeHTML(card.text)}</span>${mark}</button>`;}
function targetMarkup(id,zone,cards,bank=false){return `<section class="${bank?'bank':'drop-zone'}" data-board="${id}" data-zone="${zone.id}" aria-label="${escapeHTML(zone.label)}"><${bank?'p':'h3'} class="${bank?'workspace-label':''}">${zone.label}</${bank?'p':'h3'}>${zone.desc?`<p class="zone-desc">${zone.desc}</p>`:''}<div class="cards">${cards.map(c=>cardMarkup(id,c)).join('')}</div><button type="button" class="place-button" data-place="${zone.id}" data-board="${id}" aria-label="Place selected card in ${escapeHTML(zone.label)}">${bank?'Return selected card here':'Place here'} <span aria-hidden="true">↙</span></button></section>`;}
function boardMarkup(id){const b=boardFor(id);const isKwl=id==='kwl';const bankCards=b.cards.filter(c=>placement(id,c)==='bank');let html=`<div class="board-help"><p><strong>${isKwl?'Move your sticky notes.':'Move the cards.'}</strong> Drag, or select a card and choose Place here.</p>${!isKwl?`<button class="soft-button" data-reset="${id}">Return cards to bank</button>`:''}</div>`;
 if(isKwl)html+=`<form id="note-form" class="kwl-add"><div><label for="note-text">Add a sticky note</label><input id="note-text" maxlength="500" placeholder="An idea, question, or discovery…" required></div><div><label for="note-zone">Start in</label><select id="note-zone">${KWL_ZONES.map(z=>`<option value="${z.id}">${z.label}</option>`).join('')}</select></div><button class="primary" type="submit">Add note +</button></form><p class="small-note">Move a question when you can answer it, then add evidence in your Learn response below. Select a note to edit or remove it.</p>`;
 html+=`<div class="sort-board ${id==='language'?'language':''}" data-sort-board="${id}">${!isKwl?targetMarkup(id,{id:'bank',label:id==='language'?'Word bank':'Card bank'},bankCards,true):''}<div class="zone-grid ${id==='infer'?'four':b.zones.length===5||b.zones.length===6?'two':''}">${b.zones.map(z=>targetMarkup(id,z,b.cards.filter(c=>placement(id,c)===z.id))).join('')}</div><p class="selected-label" id="selected-${id}">${selectionMessage(id)}</p></div>`;
 if(isKwl)html+='<div class="note-tools"><button class="outline" id="edit-note">Edit selected note</button><button class="outline" id="delete-note">Remove selected note</button></div><p id="note-message" class="small-note" role="status" style="margin-top:9px"></p>';
 else html+=`<div class="actions"><button class="primary" data-check="${id}">${b.guided?'Check clue matches':id==='language'?'Check my word sort':'Check my card sort'}</button></div><div id="feedback-${id}" class="feedback" role="status" ${checked.has(id)?'':'hidden'}>${checked.has(id)?feedbackMarkup(id):''}</div>${b.guided?'<p class="check-tips">This clue match shows one useful connection. In your writing, a detail may support more than one question.</p>':''}`;
 return html;
}
function selectionMessage(id){if(selected?.board!==id)return 'No card selected. You can use drag, tap, or keyboard controls.';const card=boardFor(id).cards.find(c=>c.id===selected.card);return card?`Selected: ${escapeHTML(card.text)}. Choose Place here in a box.`:'No card selected.';}
function teacherNotes(a){const t=a.teacher;return `<details class="teacher-notes"><summary>Teacher guide · ${a.short}</summary><h2>${t.goal}</h2><ul>${t.steps.map(s=>`<li>${escapeHTML(s)}</li>`).join('')}</ul><h3>One possible response</h3><p>${escapeHTML(t.model)}</p>${t.note?`<p><strong>Discussion note:</strong> ${escapeHTML(t.note)}</p>`:''}<p class="small-note">Model responses support discussion. Students’ written answers are not automatically graded.</p></details>`;}
function renderActivity(){const a=ACTIVITIES.find(a=>a.id===state.active),i=ACTIVITIES.indexOf(a);$('main').innerHTML=`${teacher?teacherIntro():''}<div class="back-row"><button class="text-button" data-go="home">← Activity menu</button><div><label for="activity-select">Jump to </label><select id="activity-select" aria-label="Choose activity">${ACTIVITIES.map(item=>`<option value="${item.id}" ${item.id===a.id?'selected':''}>${item.short}</option>`).join('')}</select></div></div><header class="game-banner" style="--tone:var(--${a.tone})"><span class="game-number">${String(i+1).padStart(2,'0')}</span><div><p class="eyebrow">${a.type}</p><h1 id="page-heading" tabindex="-1">${a.title}</h1></div>${icon(a.icon,true)}</header><p class="activity-lead">${a.lead}</p>${a.id==='read'?readingMarkup()+safetyMarkup():`${a.id==='language'?'<div class="word-sentence">Wow! We carefully observe bright stars in the sky, and they shine.</div>':''}${boardMarkup(a.id)}${a.id==='language'?'<p class="small-note" style="margin-top:13px">Some categories have more than one example. “The” is a determiner, outside these eight categories, so it stays in the sentence.</p>':''}${fieldsMarkup(a)}<details class="self-check"><summary>Pause and check my thinking</summary><p>${a.check}</p></details>${a.id==='kwl'?`<div class="actions"><button class="outline" data-go="read">Read the passages →</button></div>`:`<details class="reading-toggle"><summary>Read ${a.source?'Reading '+a.source+' and its source card':'the classroom passages'} while you work</summary>${readingMarkup(a.source?[a.source]:['A','B'])}${safetyMarkup()}</details>`}`}${teacher?teacherNotes(a):''}<div class="next-row"><button class="outline" data-go="${i===0?'home':ACTIVITIES[i-1].id}">${i===0?'← Menu':'← Previous'}</button><button class="primary" data-go="${i===ACTIVITIES.length-1?'home':ACTIVITIES[i+1].id}">${i===ACTIVITIES.length-1?'Back to menu':'Next activity →'}</button></div>`;}
function render(){ $('student-view').setAttribute('aria-pressed',String(!teacher));$('teacher-view').setAttribute('aria-pressed',String(teacher));if(state.active==='home')renderHome();else renderActivity();}
function go(id,focus=true){if(!['home',...ACTIVITIES.map(a=>a.id)].includes(id))return;state.active=id;selected=null;render();scheduleSave();if(focus){$('page-heading').focus({preventScroll:true});$('main').scrollIntoView({block:'start',behavior:'instant'});}}
function selectCard(board,card){if(!boardFor(board)?.cards.some(c=>c.id===card))return;selected=selected?.board===board&&selected.card===card?null:{board,card};for(const el of document.querySelectorAll('[data-card]'))el.setAttribute('aria-pressed',String(selected?.board===el.dataset.board&&selected?.card===el.dataset.card));const label=$('selected-'+board);if(label)label.innerHTML=selectionMessage(board);announce(selected?'Card selected. Choose a Place here button.':'Card selection cleared.');}
function moveCard(board,cardId,zone){const b=boardFor(board),card=b?.cards.find(c=>c.id===cardId);if(!card||!['bank',...b.zones.map(z=>z.id)].includes(zone)||(board==='kwl'&&zone==='bank'))return;if(board==='kwl'){state.notes.find(n=>n.id===cardId).zone=zone;}else{state.placements[board]??={};if(zone==='bank')delete state.placements[board][cardId];else state.placements[board][cardId]=zone;}checked.delete(board);selected=null;render();scheduleSave();const target=[...document.querySelectorAll('[data-card]')].find(el=>el.dataset.board===board&&el.dataset.card===cardId);target?.focus({preventScroll:true});announce(`Moved ${card.text} to ${zone==='bank'?'the bank':b.zones.find(z=>z.id===zone).label}.`);}
function feedbackMarkup(id){const b=BOARDS[id];let placed=0,correct=0;const wrong=[];for(const c of b.cards){const p=state.placements[id]?.[c.id];if(!p)continue;placed++;if(p===c.zone)correct++;else wrong.push(c);}
 if(id==='language'){const completed=CATEGORIES.filter(cat=>b.cards.some(c=>c.zone===cat.id&&state.placements[id]?.[c.id]===cat.id)).length;if(completed===8&&!wrong.length)return `<strong>All eight categories have a correct example!</strong> ${placed===b.cards.length?'All 11 tiles are sorted correctly.':'You can keep sorting the remaining words, or explain a word’s job below.'}`;return `<strong>${completed} of 8 categories have a correct example.</strong> ${wrong.length?'Move the ↻ tiles and try again.':'Choose an example for each remaining category.'}${wrong.length?'<ul>'+wrong.map(c=>`<li>Think about the job of <strong>${c.text}</strong> in this sentence.</li>`).join('')+'</ul>':''}`;}
 if(correct===b.cards.length)return `<strong>${b.guided?'All clue matches fit the model.':'All cards are sorted correctly.'}</strong> Now explain your thinking in your own words below.`;
 return `<strong>${correct} of ${b.cards.length} cards ${b.guided?'match the model':'are correctly placed'}.</strong> ${placed<b.cards.length?'Move the cards still in the bank. ':''}${wrong.length?'Revisit the ↻ cards using these clues:':''}${wrong.length?'<ul>'+wrong.map(c=>`<li>${escapeHTML(c.reason)}</li>`).join('')+'</ul>':''}`;
}
function checkBoard(id){checked.add(id);render();const el=$('feedback-'+id);const b=BOARDS[id];const all=b.cards.every(c=>state.placements[id]?.[c.id]===c.zone);const languageComplete=id==='language'&&CATEGORIES.every(cat=>b.cards.some(c=>c.zone===cat.id&&state.placements[id]?.[c.id]===cat.id))&&b.cards.every(c=>!state.placements[id]?.[c.id]||c.zone===state.placements[id][c.id]);el.className='feedback '+(all||languageComplete?'good':'retry');announce(el.textContent);document.querySelector(`[data-check="${id}"]`).focus({preventScroll:true});}
function addNote(){const input=$('note-text'),text=input.value.trim();if(!text)return;if(state.notes.length>=60){$('note-message').textContent='Your wall has 60 notes. Edit or remove a note before adding another.';return;}state.notes.push({id:'note-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7),text,zone:$('note-zone').value});render();scheduleSave();$('note-text').focus();announce('Sticky note added.');}
function editNote(remove=false){if(selected?.board!=='kwl'){$('note-message').textContent='Select a sticky note first.';return;}const note=state.notes.find(n=>n.id===selected.card);if(!note)return;if(remove){state.notes=state.notes.filter(n=>n.id!==note.id);selected=null;render();scheduleSave();announce('Note removed.');}else{$('note-text').value=note.text;$('note-zone').value=note.zone;$('note-form').dataset.edit=note.id;$('note-form').querySelector('button[type=submit]').textContent='Update note';$('note-text').focus();}}
function submitNote(){const edit=$('note-form').dataset.edit;if(!edit){addNote();return;}const note=state.notes.find(n=>n.id===edit);const text=$('note-text').value.trim();if(note&&text){note.text=text;note.zone=$('note-zone').value;selected=null;render();scheduleSave();$('note-text').focus();announce('Sticky note updated.');}}
function downloadWork(){save();const blob=new Blob([JSON.stringify({...state,exportedAt:new Date().toISOString()},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='Space_Arcade_Work.json';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);$('file-status').textContent='Work file downloaded. Keep it to load your ideas later or share it with your teacher.';}
function hasWork(){return state.notes.length>0||Object.values(state.responses).some(row=>Object.values(row).some(v=>v.trim()))||Object.values(state.placements).some(row=>Object.keys(row).length);}
function confirmAction(description,label,action){pendingAction=action;$('confirm-description').textContent=description;$('confirm-action').textContent=label;$('confirm-dialog').showModal();}
function replaceWork(next,message){state=next;selected=null;checked.clear();save();render();$('file-status').textContent=message;$('page-heading').focus({preventScroll:true});}
async function importWork(file){try{if(!file)return;if(file.size>1000000)throw new Error('Choose a Space Arcade work file smaller than 1 MB.');const next=validateState(JSON.parse(await file.text()));const action=()=>replaceWork(next,'Work file loaded.');if(hasWork())confirmAction('Save your current work first if you want to keep it. Loading this file will replace the ideas and card positions stored in this browser.','Load this file',action);else action();}catch(error){$('file-status').textContent=error instanceof SyntaxError?'This file could not be read. Choose a saved Space Arcade JSON work file.':error.message;}finally{$('import-file').value='';}}
function preparePrint(){let html='<h1>Space Arcade — My thinking</h1><p>Grade 4 science · How do objects in space impact daily life?</p><p>Name: __________________________ &nbsp; Date: __________________</p>';for(const a of ACTIVITIES){if(a.id==='read')continue;html+=`<article class="print-activity"><h2>${a.title}</h2><p>${a.lead}</p>`;if(a.id==='kwl'){for(const z of KWL_ZONES){const notes=state.notes.filter(n=>n.zone===z.id);if(notes.length)html+=`<section><h3>${z.label} sticky notes</h3><ul>${notes.map(n=>`<li>${escapeHTML(n.text)}</li>`).join('')}</ul></section>`;}}else{const b=BOARDS[a.id];const placed=b.cards.filter(c=>state.placements[a.id]?.[c.id]);if(placed.length)html+=`<h3>My card positions</h3><table><thead><tr><th>Card</th><th>Placed in</th></tr></thead><tbody>${placed.map(c=>`<tr><td>${escapeHTML(c.text)}</td><td>${escapeHTML(b.zones.find(z=>z.id===state.placements[a.id][c.id]).label)}</td></tr>`).join('')}</tbody></table>`;}for(const f of a.fields){const v=state.responses[a.id]?.[f.key]||'';html+=`<section><h3>${f.label}</h3><p>${f.prompt}</p><p class="${v?'':'empty'}">${escapeHTML(v||'No written response yet.')}</p></section>`;}html+='</article>';}html+='<article class="print-activity"><h2>Classroom readings and sources</h2>';for(const [key,r]of Object.entries(READINGS))html+=`<section><h3>Reading ${key} · ${r.title}</h3><p>${escapeHTML(r.text)}</p><p>Adapted from NASA. Original: ${r.original}. ${r.url}</p></section>`;html+='<p>Observe with an adult. Never look directly at the Sun or point binoculars or a telescope at it.</p></article>';$('print-content').innerHTML=html;}
// One pointer interaction supports mouse, pen, and touch; tap/keyboard remains available.
document.addEventListener('pointerdown',event=>{const card=event.target.closest('[data-card]');if(!card||event.button!==0)return;drag={pointer:event.pointerId,board:card.dataset.board,card:card.dataset.card,element:card,startX:event.clientX,startY:event.clientY,x:event.clientX,y:event.clientY,moved:false,ghost:null};card.setPointerCapture(event.pointerId);});
document.addEventListener('pointermove',event=>{if(!drag||drag.pointer!==event.pointerId)return;drag.x=event.clientX;drag.y=event.clientY;if(!drag.moved&&Math.hypot(event.clientX-drag.startX,event.clientY-drag.startY)>9){drag.moved=true;drag.ghost=drag.element.cloneNode(true);drag.ghost.removeAttribute('data-card');drag.ghost.removeAttribute('id');drag.ghost.setAttribute('aria-hidden','true');drag.ghost.classList.add('drag-ghost');drag.ghost.style.width=Math.min(drag.element.offsetWidth,260)+'px';document.body.append(drag.ghost);}if(!drag.moved)return;event.preventDefault();drag.ghost.style.left=event.clientX-30+'px';drag.ghost.style.top=event.clientY-22+'px';document.querySelectorAll('.drop-hover').forEach(el=>el.classList.remove('drop-hover'));const zone=document.elementFromPoint(event.clientX,event.clientY)?.closest('[data-zone]');if(zone?.dataset.board===drag.board)zone.classList.add('drop-hover');if(event.pointerType==='mouse'){if(event.clientY>window.innerHeight-50)window.scrollBy(0,14);else if(event.clientY<80)window.scrollBy(0,-14);}});
document.addEventListener('pointerup',event=>{if(!drag||drag.pointer!==event.pointerId)return;const current=drag;drag=null;current.ghost?.remove();document.querySelectorAll('.drop-hover').forEach(el=>el.classList.remove('drop-hover'));if(!current.moved)return;suppressClick=true;setTimeout(()=>suppressClick=false,0);const zone=document.elementFromPoint(event.clientX,event.clientY)?.closest('[data-zone]');if(zone?.dataset.board===current.board)moveCard(current.board,current.card,zone.dataset.zone);else announce('Card returned. Drag it into a box, or select it and use Place here.');});
document.addEventListener('pointercancel',()=>{drag?.ghost?.remove();drag=null;document.querySelectorAll('.drop-hover').forEach(el=>el.classList.remove('drop-hover'));});
document.addEventListener('click',event=>{if(suppressClick&&event.detail>0){event.preventDefault();return;}const nav=event.target.closest('[data-go]');if(nav){go(nav.dataset.go);return;}const card=event.target.closest('[data-card]');if(card){selectCard(card.dataset.board,card.dataset.card);return;}const place=event.target.closest('[data-place]');if(place){if(selected?.board===place.dataset.board)moveCard(selected.board,selected.card,place.dataset.place);else announce('Select a card first, then choose Place here.');return;}const check=event.target.closest('[data-check]');if(check){checkBoard(check.dataset.check);return;}const reset=event.target.closest('[data-reset]');if(reset){state.placements[reset.dataset.reset]={};checked.delete(reset.dataset.reset);selected=null;render();scheduleSave();announce('Cards returned to the bank.');return;}const close=event.target.closest('[data-close]');if(close)$(close.dataset.close).close();if(event.target.id==='edit-note')editNote();if(event.target.id==='delete-note')editNote(true);});
document.addEventListener('input',event=>{const el=event.target;if(!el.matches('textarea[data-field]')||!allowedFields[el.dataset.activity]?.has(el.dataset.field))return;state.responses[el.dataset.activity]??={};state.responses[el.dataset.activity][el.dataset.field]=el.value;scheduleSave();});
document.addEventListener('submit',event=>{if(event.target.id==='note-form'){event.preventDefault();submitNote();}});
document.addEventListener('change',event=>{if(event.target.id==='activity-select')go(event.target.value);});
$('student-view').addEventListener('click',()=>{teacher=false;render();announce('Student view.');});$('teacher-view').addEventListener('click',()=>{teacher=true;render();announce('Teacher view. Teaching guides are now available.');});
$('export').addEventListener('click',downloadWork);$('import').addEventListener('click',()=>$('import-file').click());$('import-file').addEventListener('change',e=>importWork(e.target.files[0]));$('print').addEventListener('click',()=>{save();preparePrint();window.print();});$('help').addEventListener('click',()=>$('help-dialog').showModal());
$('new-learner').addEventListener('click',()=>{$('help-dialog').close();confirmAction('Save work first if you want to keep your ideas. New learner clears this app’s notes, responses, and card positions in this browser.','Start fresh',()=>{teacher=false;replaceWork(freshState(),'Ready for a new learner.');});});
$('cancel-confirm').addEventListener('click',()=>{pendingAction=null;$('confirm-dialog').close();});$('confirm-action').addEventListener('click',()=>{const action=pendingAction;pendingAction=null;$('confirm-dialog').close();action?.();});$('confirm-dialog').addEventListener('cancel',()=>pendingAction=null);
window.addEventListener('beforeprint',preparePrint);window.addEventListener('pagehide',save);window.addEventListener('keydown',event=>{if(event.key==='Escape'&&selected){selected=null;document.querySelectorAll('[data-card]').forEach(el=>el.setAttribute('aria-pressed','false'));const label=$('selected-'+state.active);if(label)label.innerHTML=selectionMessage(state.active);announce('Card selection cleared.');}});
initStorage();render();
