const APP_TITLE='Word Detective';
const rng=MorphCore.random((Date.now()^Math.floor(Math.random()*1000000))>>>0);
let route='cases', filter='All cases', current=null, stage='sort', assignments={}, selectedCard=null, orderedCards=[], sortSolved=false, wrongIds=[], checked=false, supported=false, hint=false, message='', messageType='success', chosen=null, answered=false, evidenceOptions=[], applyOptions=[], reflection='', solved={}, printCase='flow';
function openCase(id){current=DATA.cases.find(c=>c.id===id);if(!current)return;route='cases';stage='sort';assignments={};selectedCard=null;orderedCards=MorphCore.shuffle(current.cards,rng);sortSolved=false;wrongIds=[];checked=false;supported=false;hint=false;message='';chosen=null;answered=false;reflection='';evidenceOptions=MorphCore.shuffle(current.evidence.answers,rng);applyOptions=MorphCore.shuffle(current.apply.answers,rng);printCase=id;render(true);}
function home(){const visible=DATA.cases.filter(c=>filter==='All cases'||c.kind===filter);return `<section class="hero"><div><p class="eyebrow">Word Detective · investigate & sort</p><h1>Follow the meaning.<br>Find the family.</h1><p class="lead">Look closely, test a theory, and explain your evidence. Similar letters can be a clue—but a word’s meaning has the final say.</p><div class="row space"><span class="pill">10 investigations</span><span class="pill">Word families & affix jobs</span></div></div><div class="hero-visual"><p class="eyebrow">Case file 01</p><h2>The flower puzzle</h2><div class="case-preview"><div class="tiles">${tile('flow','base','move like water')}<span class="symbol">→</span>${tile('flowing','base','same base')}</div></div><div class="case-preview" style="border-color:#d9cedf;background:#fcfafc"><div class="tiles">${tile('flower','prefix','a different base')}</div><p class="smalltext muted space-sm">A bloom, not “someone who flows”.</p></div><p class="tiny muted">Family members share a meaningful base. A matching letter string is something to investigate, not proof.</p></div></section>
 <div class="section-head"><div><h2>Choose a case</h2><p>Sort six cards, explain a pattern, then use it in a sentence.</p></div>${current&&stage!=='complete'?button('Resume my case','resume','','quiet'):''}</div><div class="toggle-row" aria-label="Case filters">${['All cases','Word families','Affix jobs'].map(f=>button(e(f),'filter',`data-filter="${e(f)}" aria-pressed="${f===filter}"`)).join('')}</div><section class="case-grid">${visible.map(c=>`<article class="card"><p class="case-number">Case ${String(DATA.cases.indexOf(c)+1).padStart(2,'0')} · ${e(c.kind)}</p><h3>${e(c.title)}</h3><p>${e(c.intro)}</p><div class="actions">${button(solved[c.id]?'Investigate again →':'Open case →','open',`data-id="${c.id}"`,'primary')}${solved[c.id]?'<span class="pill"><span aria-hidden="true">✓</span> Case solved</span>':''}</div></article>`).join('')}</section><div class="info-strip space"><span><strong>Tap or keyboard</strong> sorting</span><span><strong>Specific feedback</strong> for every card</span><span><strong>Printables</strong> with answer keys</span></div>`;}
function head(){return `<div class="workhead"><div><p class="eyebrow">Case ${String(DATA.cases.indexOf(current)+1).padStart(2,'0')} · ${e(current.kind)}</p><h1>${e(current.title)}</h1></div><div class="row">${button('All cases','all','','small quiet')}${stage!=='complete'?button('Hint','hint','','small'):''}</div></div><div class="steps">${['sort','evidence','apply'].map((s,i)=>`<span class="${s===stage?'active':stage==='complete'||['sort','evidence','apply'].indexOf(stage)>i?'complete':''}">${i+1} · ${['Sort','Explain','Apply'][i]}</span>`).join('')}</div>`;}
function sort(){const active=current.cards.find(c=>c.id===selectedCard);const unassigned=orderedCards.filter(c=>!assignments[c.id]);return `<h2>Sort the evidence cards</h2><p class="muted space-sm">${e(current.intro)}</p><p class="smalltext space"><strong>1.</strong> Select a card. <strong>2.</strong> Select its group. To move a placed card, return it to the pool first.</p><div class="pool space-sm" aria-label="Unsorted cards">${unassigned.length?unassigned.map(c=>button(`<strong>${e(c.word)}</strong>${c.sentence?`<small>${e(c.sentence)}</small>`:''}`,'select-card',`data-id="${c.id}" aria-pressed="${c.id===selectedCard}"`,'sort-card'+(c.id===selectedCard?' selected':''))).join(''):`<p class="muted smalltext">All six cards are placed. Check your evidence.</p>`}</div><div class="row space-sm" id="selection-tools"><span class="tiny muted" role="status">${active?`Selected: ${e(active.word)}${active.sentence?' — '+e(active.sentence):''}`:'Select a card to choose a group.'}</span>${active?button('Hear this card','speak',`data-text="${e(active.sentence||active.word)}"`,'small'):''}</div><div class="sort-groups" style="--group-count:${current.groups.length}">${current.groups.map(g=>{const members=orderedCards.filter(c=>assignments[c.id]===g.id);return `<section class="sort-group">${button(`${e(g.label)}<small>${e(g.detail)}</small>`,'put-card',`data-group="${g.id}" ${!active||sortSolved?'disabled':''} aria-label="${e(active?'Place '+active.word+' in '+g.label:g.label)}"`)}<ul aria-label="Cards in ${e(g.label)}">${members.map(c=>`<li>${button(`${checked&&!wrongIds.includes(c.id)?'✓ ':wrongIds.includes(c.id)?'↺ ':''}${e(c.word)}${c.sentence?`<small class="muted" style="display:block;font-weight:600;font-size:.75rem">${e(c.sentence)}</small>`:''}`,'return-card',`data-id="${c.id}" ${sortSolved?'disabled':''} aria-label="Return ${e(c.word)}${c.sentence?' — '+e(c.sentence):''} to the pool"`,wrongIds.includes(c.id)?'wrong':checked?'correct':'')}</li>`).join('')}</ul>${!members.length?'<p class="empty-group">Cards placed here will appear below.</p>':''}</section>`;}).join('')}</div><div class="actions">${sortSolved?button('Investigate the pattern →','to-evidence','','primary'):button('Check my sort','check-sort',`${unassigned.length?'disabled':''}`,'primary')}${!sortSolved?button('Clear this sort','clear-sort'):''}</div>${checked?`<div class="evidence-list">${(sortSolved?current.cards:current.cards.filter(c=>wrongIds.includes(c.id))).map(c=>`<div><strong>${e(c.word)}${c.sentence?' — '+e(c.sentence):''}</strong>${e(c.evidence)}</div>`).join('')}</div>`:''}`;}
function questionView(){const q=stage==='evidence'?current.evidence:current.apply;const choices=stage==='evidence'?evidenceOptions:applyOptions;return `<p class="eyebrow">${stage==='evidence'?'Explain the pattern':'Use your discovery'}</p><h2>${e(q.prompt)}</h2>${stage==='evidence'?`<div class="info-strip space">${current.cards.slice(0,4).map(c=>`<span><strong>${e(c.word)}</strong></span>`).join('')}</div>`:''}<div class="answers">${choices.map(a=>button(e(a),'answer',`data-answer="${e(a)}" ${answered?'disabled':''}`,chosen===a?(answered?'correct':'incorrect'):'')).join('')}</div>${answered?stage==='evidence'?`<div class="actions">${button('Apply it in context →','to-apply','','primary')}</div>`:`<label class="field wide space">My evidence <span class="tiny muted" style="font-weight:600">Optional: explain the base or affix in your own words. You can discuss it aloud instead.</span><textarea id="reflection" placeholder="The word’s parts help me because…" maxlength="1500">${e(reflection)}</textarea></label><div class="actions">${button('Solve this case →','finish','','primary')}</div>`:''}`;}
function completed(){return `<p class="eyebrow">Case solved</p><h2>You followed the evidence.</h2><p class="lead">${e(current.tip)}</p><div class="info-strip space"><span><strong>6 cards</strong> sorted by meaning or job</span><span><strong>Pattern</strong> explained</span><span><strong>Context</strong> investigated</span></div><div class="evidence-list">${current.cards.map(c=>`<div><strong>${e(c.word)}${c.sentence?' — '+e(c.sentence):''}</strong>${e(c.evidence)}</div>`).join('')}</div>${reflection?`<div class="feedback space"><h3>My evidence</h3><p>${e(reflection)}</p></div>`:''}<p class="note space">${supported?'You solved this case with hints or retries. Revisit it later and see which ideas you remember.':'You solved this case without hints or retries.'} This describes the activity, not a reading level or grade.</p><div class="actions">${button('Choose another case','all','','primary')}${button('Print my case notes','print-notes')}${button('Investigate again','open',`data-id="${current.id}"`)}</div>`;}
function investigation(){return `<div class="solo">${head()}<section class="card">${stage==='sort'?sort():stage==='complete'?completed():questionView()}${message?feedback(message,messageType):''}${hint&&stage!=='complete'?feedback(stage==='sort'?current.tip:stage==='evidence'?current.evidence.explanation:current.apply.explanation,'hint','A clue to investigate'):''}</section></div>`;}
function teacher(){return `<div class="section-head"><div><p class="eyebrow">Teacher corner</p><h1 style="font-size:2.7rem">Ask “What is your evidence?”</h1><p>Designed for roughly Grades 3–6, with discussion and reading support as needed.</p></div></div><div class="split"><section class="card"><h2>A detective routine</h2><div class="evidence-list"><div><strong>Notice</strong>Read each card aloud. Name a possible base or affix. Treat a matching letter string as a question to investigate.</div><div><strong>Test</strong>Sort by a meaningful relationship or grammatical job. Use the context sentence. Explain a decision before checking it.</div><div><strong>Apply</strong>Discuss the evidence question. Write a new sentence using the word. Look for a related example in classroom reading.</div></div><p class="note space">Word-family cases focus on the stated base and its meaning. Related spellings or deep historical connections alone do not automatically place a word in that base family.</p></section><section class="card"><h2>Print a case file</h2><p>Sort the words on paper, explain the pattern, and use your discovery in context.</p><label class="field space">Investigation<select id="print-case">${DATA.cases.map(c=>`<option value="${c.id}" ${c.id===printCase?'selected':''}>${e(c.title)}</option>`).join('')}</select></label><div class="actions">${button('Print activity','print',`data-key="false"`,'primary')}${button('Print with answer key','print',`data-key="true"`)}</div><p class="tiny muted space">The answer key explains every card. A printed activity does not show multiple-choice answers.</p></section></div><section class="card space"><h2>Teaching details</h2><p>Six cases investigate bases, including compounds and spelling changes. Four compare affix jobs: -er, -s, un- and the three sounds of past-tense -ed.</p><p>Read both <strong>paints</strong> cards carefully: their sentences give them different jobs. Make each decision from the word and its context.</p><p>Read-aloud uses an available browser voice. For the -ed case, say the words together if pronunciation is unclear.</p><div class="actions">${button('Reset solved-case marks','reset')}</div><p class="tiny muted space">Marks last while this tab stays open. They do not record names or written responses.</p></section><div class="space">${researchPanel()}</div>`;}
function printable(key,notes=false){const c=notes?current:DATA.cases.find(c=>c.id===printCase);const sheet=`<p>${e(c.title)} · Name: ____________________ &nbsp; Date: ______________</p><p>${e(c.intro)}</p><h2>1 · Sort the evidence</h2><div class="print-word-list">${c.cards.map((a,i)=>`${i+1}. ${e(a.word)}${a.sentence?' — '+e(a.sentence):''}`).join('<br>')}</div><table><thead><tr>${c.groups.map(g=>`<th>${e(g.label)}<br><span style="font-weight:normal">${e(g.detail)}</span></th>`).join('')}</tr></thead><tbody><tr>${c.groups.map(g=>`<td style="height:110px">${notes?c.cards.filter(a=>a.group===g.id).map(a=>e(a.word)+(a.sentence?' — '+e(a.sentence):'')).join('<br>'):''}</td>`).join('')}</tr></tbody></table><div class="keep"><h2>2 · Explain the pattern</h2><p>${e(c.evidence.prompt)}</p>${notes?`<p>${e(c.evidence.answers[0])}</p>`:'<div class="writing-lines"></div><div class="writing-lines"></div>'}</div><div class="keep"><h2>3 · Apply your discovery</h2><p>${e(c.apply.prompt)}</p>${notes?`<p>${e(c.apply.answers[0])}</p><p>My evidence: ${e(reflection||'Discussed aloud.')}</p>`:'<div class="writing-lines"></div><div class="writing-lines"></div>'}</div><p class="print-footer">Word Detective · interactives.blackgold.ca/word-detective/</p>`;const answers=key?`<section class="key"><h2>Teacher answer key · ${e(c.title)}</h2><table><thead><tr><th>Card</th><th>Group</th><th>Evidence</th></tr></thead><tbody>${c.cards.map(a=>`<tr><td>${e(a.word)}${a.sentence?'<br>'+e(a.sentence):''}</td><td>${e(c.groups.find(g=>g.id===a.group).label)}</td><td>${e(a.evidence)}</td></tr>`).join('')}</tbody></table><h3 style="margin-top:18px">Explain</h3><p>${e(c.evidence.answers[0])} ${e(c.evidence.explanation)}</p><h3>Apply</h3><p>${e(c.apply.answers[0])} ${e(c.apply.explanation)}</p><p>Accept accurate explanations in learners’ own words.</p></section>`:'';printPage(notes?'Word Detective — my case notes':'Word Detective — case file',sheet+answers);}
function render(focus=false){navActive(route);draw(route==='teacher'?teacher():current?investigation():home(),focus);}
function focusNextCard(){const target=main.querySelector('.pool button')||main.querySelector('[data-action="check-sort"]');target?.focus({preventScroll:true});}
document.addEventListener('click',event=>{const b=event.target.closest('button[data-action]');if(!b||b.disabled||b.dataset.action==='speak')return;const action=b.dataset.action;
 if(action==='route'){route=b.dataset.route;render(true);return;}
 if(action==='all'){current=null;route='cases';render(true);return;}
 if(action==='resume'){route='cases';render(true);return;}
 if(action==='filter'){filter=b.dataset.filter;render();return;}
 if(action==='open'){openCase(b.dataset.id);return;}
 if(action==='select-card'){
 selectedCard=b.dataset.id;message='';const active=current.cards.find(c=>c.id===selectedCard);
 main.querySelectorAll('button[data-action="select-card"]').forEach(card=>{const isSelected=card.dataset.id===selectedCard;card.setAttribute('aria-pressed',String(isSelected));card.classList.toggle('selected',isSelected);});
 main.querySelectorAll('button[data-action="put-card"]').forEach(group=>{group.disabled=false;group.setAttribute('aria-label','Place '+active.word+' in '+current.groups.find(g=>g.id===group.dataset.group).label);});
 main.querySelector('#selection-tools').innerHTML=`<span class="tiny muted" role="status">Selected: ${e(active.word)}${active.sentence?' — '+e(active.sentence):''}</span>${button('Hear this card','speak',`data-text="${e(active.sentence||active.word)}"`,'small')}`;
 main.querySelectorAll('.feedback.error').forEach(f=>f.remove());announce('Card selected. Choose a group.');return;
 }
 if(action==='put-card'){if(!selectedCard)return;assignments[selectedCard]=b.dataset.group;selectedCard=null;wrongIds=[];checked=false;message='';render();focusNextCard();return;}
 if(action==='return-card'){delete assignments[b.dataset.id];selectedCard=b.dataset.id;wrongIds=[];checked=false;message='';render();return;}
 if(action==='check-sort'){wrongIds=MorphCore.wrongGroups(assignments,current.cards);checked=true;sortSolved=wrongIds.length===0;if(!sortSolved)supported=true;message=sortSolved?'All six cards fit their groups. Read the explanations, then investigate the pattern.':`${wrongIds.length} ${wrongIds.length===1?'card needs':'cards need'} another look. Read the evidence below, return those cards to the pool, and try a different group.`;messageType=sortSolved?'success':'error';announce(message);render();return;}
 if(action==='clear-sort'){assignments={};selectedCard=null;wrongIds=[];checked=false;message='';render();focusNextCard();return;}
 if(action==='hint'){supported=true;hint=true;announce('A clue is shown below the activity.');render();return;}
 if(action==='to-evidence'){stage='evidence';chosen=null;answered=false;hint=false;message='';render(true);return;}
 if(action==='answer'){const q=stage==='evidence'?current.evidence:current.apply;chosen=b.dataset.answer;answered=chosen===q.answers[0];if(!answered)supported=true;message=answered?q.explanation:'Revisit the word’s base, affix and meaning in this context. Try another explanation, or use a hint.';messageType=answered?'success':'error';announce(message);render();return;}
 if(action==='to-apply'){stage='apply';chosen=null;answered=false;hint=false;message='';render(true);return;}
 if(action==='finish'){stage='complete';solved[current.id]={supported};hint=false;message='';render(true);return;}
 if(action==='reset'){solved={};announce('Solved-case marks cleared.');render();return;}
 if(action==='print'){printable(b.dataset.key==='true');return;}
 if(action==='print-notes'){printable(false,true);return;}
});
document.addEventListener('change',event=>{if(event.target.id==='print-case')printCase=event.target.value;});
document.addEventListener('input',event=>{if(event.target.id==='reflection')reflection=event.target.value;});
render();
