const APP_TITLE='Morpheme Missions';
let route='game', level='start', printLevel='start', deck=[], round=0, stage='build', selected=[null,null,null], buildOptions=[], meaningOptions=[], spellingOptions=[], message='', messageType='success', hinted=false, supported=false, answered=false, chosen=null, results=[], labBase='help', labWord='helpful';
const rng=MorphCore.random((Date.now()^Math.floor(Math.random()*1000000))>>>0);
const prefixPool=['','re','un','mis','pre','dis'];
const suffixPool=['','ful','less','ness','er','ed','ing','ly'];
const basePool=[...new Set(DATA.missions.map(m=>m.parts[1]))];
const allWords=[...DATA.missions,...DATA.extras];
function partMeaning(m,index){const p=m.parts[index];if(!p)return 'No affix needed here.';if(index===1)return DATA.bases[p]||'The base carries the word’s main meaning.';return (index===0?m.prefixJob:m.suffixJob)||DATA.partMeanings[p];}
function start(newLevel,reviewIds=null){level=newLevel;printLevel=newLevel;const pool=DATA.missions.filter(m=>reviewIds?reviewIds.includes(m.id):m.level===level);deck=MorphCore.shuffle(pool,rng).slice(0,reviewIds?pool.length:6);round=0;results=[];route='game';navActive(route);newRound();render(true);}
function newRound(){selected=[null,null,null];stage='build';message='';hinted=false;supported=false;answered=false;chosen=null;const m=deck[round];buildOptions=[MorphCore.options(m.parts[0],prefixPool,rng),MorphCore.options(m.parts[1],basePool,rng),MorphCore.options(m.parts[2],suffixPool,rng)];meaningOptions=MorphCore.shuffle(m.meanings,rng);spellingOptions=MorphCore.shuffle(m.spellings,rng);}
function home(){return `<section class="hero"><div><p class="eyebrow">Morpheme Missions · word-building game</p><h1>Small parts.<br>Big discoveries.</h1><p class="lead">Build a word that fits. Discover what each part means, then investigate how its spelling comes together.</p><div class="row space"><span class="pill">36 missions</span><span class="pill">Three starting points</span><span class="pill">No timer</span></div></div><div class="hero-visual"><p class="eyebrow">Your first discovery</p><div class="tiles">${sumTiles(['un','help','ful'])}</div><p class="bigword">unhelpful</p><p class="muted">Not helpful. Three meaningful parts, one useful word.</p><div class="sum">un + help + ful → unhelpful</div><p class="tiny muted">A <strong>morpheme</strong> is a small unit that carries meaning or a grammatical job. A base holds the central meaning; affixes add or change something.</p></div></section>
  <section><div class="section-head"><div><h2>Choose a mission set</h2><p>Six words per round. Try a hint whenever you need one.</p></div>${deck.length&&round<deck.length?button('Resume my round','resume','','quiet'):''}</div><div class="cards">${Object.entries(DATA.levels).map(([id,l],i)=>`<article class="card"><p class="eyebrow">0${i+1}</p><h3>${e(l.title)}</h3><p>${e(l.detail)}</p>${button('Start six missions →','start',`data-level="${id}"`,'primary')}</article>`).join('')}</div></section>
  <div class="info-strip space"><span><strong>Build</strong> with bases and affixes</span><span><strong>Check</strong> the spelling boundary</span><span><strong>Explain</strong> the meaning in context</span></div><section class="card space"><div class="row between"><div><h3>Prefer to explore?</h3><p>Open the Word Lab to compare real members of a word family.</p></div>${button('Visit the Word Lab','route',`data-route="lab"`)}</div></section>`;}
function steps(m){const current=stage==='build'?0:stage==='spell'?1:2;const labels=m.spellings.length?['1 · Build','2 · Spell','3 · Explain']:['1 · Build','2 · Explain'];return `<div class="steps" aria-label="Activity steps">${labels.map((s,i)=>`<span class="${i===(m.spellings.length?current:current===0?0:1)?'active':i<(m.spellings.length?current:current===0?0:1)?'complete':''}">${s}</span>`).join('')}</div>`;}
function workhead(){return `<div class="workhead"><div><p class="eyebrow">${e(DATA.levels[level].title)}</p><h1>Mission ${round+1} of ${deck.length}</h1><div class="progress" aria-label="${round} missions completed">${deck.map((_,i)=>`<span class="${i<round?'done':i===round?'current':''}"></span>`).join('')}</div></div><div class="row">${button('Choose a set','home','','small quiet')}${button('Hint','hint','','small')}</div></div>`;}
function sentence(m,reveal=false){return e(m.sentence).replace('___',`<span class="blank">${reveal?e(m.word):'?'}</span>`);}
function game(){if(!deck.length)return home();if(round>=deck.length)return complete();const m=deck[round];let content='';
  if(stage==='build')content=`<p class="eyebrow">Read the sentence</p><p class="sentence">${sentence(m)}</p><div class="clue"><strong>Meaning clue:</strong> ${e(m.meanings[0])}</div><h2>Choose the meaningful parts</h2><p class="muted smalltext space-sm">Choose one tile in each column. “No prefix” and “No suffix” are useful choices, too.</p><div class="picker space">${['Prefix','Base','Suffix'].map((label,i)=>`<section class="pick-group"><h3>${label}<small>${i===0?'Goes before the base':i===1?'Holds the central meaning':'Goes after the base'}</small></h3>${buildOptions[i].map(p=>button(e(p?(i===0?p+'-':i===2?'-'+p:p):i===0?'No prefix':'No suffix'),'pick',`data-column="${i}" data-part="${e(p)}" aria-pressed="${selected[i]===p}"`)).join('')}</section>`).join('')}</div><div class="sum" aria-label="Your word sum">${selected.map(p=>p===null?'□':p||'—').join(' + ')}</div><div class="actions">${button('Check my parts','check-build',`${selected.some(p=>p===null)?'disabled':''}`,'primary')}${button('Read the sentence','speak',`data-text="${e(m.sentence.replace('___','blank'))}"`)}</div>`;
  if(stage==='spell')content=`<p class="eyebrow">The parts are right</p><h2>What happens at the spelling boundary?</h2><p class="sum">${e(MorphCore.wordSum(m.parts))} → ?</p><p class="muted">Keep the full base in the word sum. Choose the finished word’s spelling.</p><div class="answers">${spellingOptions.map(w=>button(e(w),'answer-spell',`data-answer="${e(w)}" ${answered?'disabled':''}`,(chosen===w?(answered?'correct':'incorrect'):''))).join('')}</div>${answered?`<div class="actions">${button('Explain the meaning →','to-meaning','','primary')}</div>`:''}`;
  if(stage==='meaning')content=`<p class="eyebrow">Now connect it to meaning</p><div class="tiles">${sumTiles(m.parts)}</div><p class="sum">${e(MorphCore.wordSum(m.parts))} → ${e(m.word)}</p><p class="sentence">${sentence(m,true)}</p><h2>Which meaning fits this sentence?</h2><div class="answers">${meaningOptions.map(a=>button(e(a),'answer-meaning',`data-answer="${e(a)}" ${answered?'disabled':''}`,(chosen===a?(answered?'correct':'incorrect'):''))).join('')}</div>${answered?`<div class="meaning-notes">${m.parts.map((p,i)=>p?`<div class="meaning-note"><strong>${e(i===0?p+'-':i===2?'-'+p:p)}</strong>${e(partMeaning(m,i))}</div>`:'').join('')}</div>${m.rule?`<p class="note space">${e(m.rule)}</p>`:''}<div class="actions">${button(round===deck.length-1?'Finish my round →':'Next mission →','next','','primary')}${button('Hear the word','speak',`data-text="${e(m.word)}"`)}</div>`:''}`;
  return `<div class="solo">${workhead()}${steps(m)}<section class="card">${content}${message?feedback(message,messageType):''}${hinted&&!answered?feedback(stage==='build'?`Start with the full base ${m.parts[1]}. ${m.parts[0]?m.parts[0]+'- means '+partMeaning(m,0)+'.':'No prefix is needed.'} ${m.parts[2]?'-'+m.parts[2]+' '+partMeaning(m,2)+'.':'No suffix is needed.'}`:stage==='spell'?m.rule:`Read the sentence again. Think about the jobs of ${MorphCore.wordSum(m.parts)}.`,'hint','Try this clue'):''}</section></div>`;}
function complete(){const stats=MorphCore.summary(results);const supportedIds=results.filter(x=>x.supported).map(x=>x.id);return `<section class="card solo"><p class="eyebrow">Round complete</p><h1 class="success-title">You built ${stats.completed} words.</h1><p class="lead">Your explanations connect small word parts to bigger meanings. Keep noticing these words when you read and write.</p><div class="stat-grid"><div class="stat"><strong>${stats.independent}</strong><span>Completed without hints or retries</span></div><div class="stat"><strong>${stats.supported}</strong><span>Practised with support</span></div></div><div class="evidence-list">${results.map(r=>{const m=DATA.missions.find(m=>m.id===r.id);return `<div><strong>${e(MorphCore.wordSum(m.parts))} → ${e(m.word)}</strong>${e(m.meanings[0])}${m.rule?`<p class="tiny space-sm">${e(m.rule)}</p>`:''}</div>`;}).join('')}</div><div class="actions">${supportedIds.length?button('Revisit supported words','review','','primary'):button('Try six more','start',`data-level="${level}"`,'primary')}${button('Choose another set','home')}${button('Print these missions','print',`data-key="false"`)}</div><p class="note space">Try a transfer task: find or write a new sentence using one word from the round. Discuss how the word’s parts help with its meaning.</p></section>`;}
function lab(){const bases=[...new Set(allWords.map(m=>m.parts[1]))].sort();const words=allWords.filter(m=>m.parts[1]===labBase);let m=words.find(m=>m.word===labWord)||words[0];labWord=m.word;return `<div class="section-head"><div><p class="eyebrow">Word Lab · explore at your own pace</p><h1 style="font-size:2.6rem">Same base. New possibilities.</h1><p>Compare real words. Word sums keep the full base visible.</p></div></div><div class="split"><section class="card"><label class="field">Choose a base<select id="lab-base">${bases.map(b=>`<option value="${e(b)}" ${b===labBase?'selected':''}>${e(b)} · ${e(DATA.bases[b]||'')}</option>`).join('')}</select></label><div class="sum">Base: ${e(labBase)} <span class="muted smalltext">· ${e(DATA.bases[labBase])}</span></div><h3>Investigate a word</h3><div class="library">${words.map(w=>button(e(w.word),'lab-word',`data-word="${e(w.word)}" aria-pressed="${w.word===m.word}"`)).join('')}</div><p class="note">These are selected real words, not every possible member of the family. Not every prefix and suffix can combine with every base.</p></section><section class="card"><p class="eyebrow">${e(m.word)}</p><div class="tiles">${sumTiles(m.parts)}</div><p class="sum">${e(MorphCore.wordSum(m.parts))} → ${e(m.word)}</p><h3>${e(m.meanings[0])}</h3><p>${e(m.sentence.replace('___',m.word))}</p>${m.rule?feedback(m.rule,'hint','Notice the spelling'):feedback('The parts join without changing the base spelling.')}<div class="actions">${button('Hear the word','speak',`data-text="${e(m.word)}"`)}</div></section></div><section class="card space"><h3>Talk about your discovery</h3><p>What stays the same? What changes? Explain the affix’s job, then use the word in a sentence of your own.</p></section>`;}
function teacher(){return `<div class="section-head"><div><p class="eyebrow">Teacher corner</p><h1 style="font-size:2.7rem">Make the thinking visible.</h1><p>Designed for roughly Grades 3–6. Use adult-supported examples with younger learners.</p></div></div><div class="split"><section class="card"><h2>A short teaching routine</h2><div class="evidence-list"><div><strong>1 · Model one word</strong>Read a sentence, name the full base, and explain the prefix or suffix. Use a word sum.</div><div><strong>2 · Practise and compare</strong>Play six missions with a partner. Ask students to explain a choice before checking it.</div><div><strong>3 · Return to reading and writing</strong>Find another family member in a text. Write a new sentence and explain the meaning. Revisit the words later.</div></div><p class="note space">“Without hints or retries” describes this round only. It is not a reading level, grade or diagnostic score.</p></section><section class="card"><h2>Take it off screen</h2><p>Print a six-word activity with room for word sums, spellings and explanations.</p><label class="field space">Mission set<select id="print-level">${Object.entries(DATA.levels).map(([id,l])=>`<option value="${id}" ${id===printLevel?'selected':''}>${e(l.title)}</option>`).join('')}</select></label><div class="actions">${button('Print activity','print',`data-key="false"`,'primary')}${button('Print with answer key','print',`data-key="true"`)}</div><p class="tiny muted space">If a round is active for this set, printing uses its words. Otherwise, it uses the first six words in the set.</p></section></div><section class="card space"><h2>What is in the bank?</h2><p>36 game missions, plus six comparison words in the Word Lab. Silent-e removal, y-to-i and consonant doubling are taught through specific examples; these are not universal rules without exceptions.</p><div class="wordbank space">${DATA.missions.map(m=>button(e(m.word),'preview',`data-word="${e(m.word)}"`)).join('')}</div></section><div class="space">${researchPanel()}</div>`;}
function printable(key){const items=deck.length&&DATA.missions.find(m=>m.id===deck[0].id)?.level===printLevel?deck:DATA.missions.filter(m=>m.level===printLevel).slice(0,6);const sheet=`<p>${e(DATA.levels[printLevel].title)} · Name: ____________________ &nbsp; Date: ______________</p><p>Read each sentence. Build a word from meaningful parts. Write the full base in a word sum, then write the finished spelling and explain its meaning.</p>${items.map((m,i)=>`<section class="print-item"><h3>${i+1}. ${e(m.sentence.replace('___','____________'))}</h3><p>Meaning clue: ${e(m.meanings[0])}</p><p>Word sum: _______________________________________________________</p><p>Finished spelling: ____________________________</p><p>Explain the meaning in your own words:</p><div class="writing-lines"></div></section>`).join('')}<p class="print-footer">Morpheme Missions · interactives.blackgold.ca/morpheme-missions/</p>`;const answers=key?`<section class="key"><h2>Teacher answer key</h2>${items.map((m,i)=>`<section class="print-item"><h3>${i+1}. ${e(MorphCore.wordSum(m.parts))} → ${e(m.word)}</h3><p>${e(m.meanings[0])}</p>${m.rule?`<p>${e(m.rule)}</p>`:''}<p>${m.parts.map((p,j)=>p?e(p+': '+partMeaning(m,j)):'').filter(Boolean).join('; ')}</p></section>`).join('')}<p>Accept accurate explanations in students’ own words. Ask learners to write a new sentence as an extension.</p></section>`:'';printPage('Morpheme Missions — activity',sheet+answers);}
function render(focus=false){navActive(route);draw(route==='game'?game():route==='lab'?lab():teacher(),focus);}
document.addEventListener('click',event=>{const b=event.target.closest('button[data-action]');if(!b||b.disabled||b.dataset.action==='speak')return;const action=b.dataset.action;const m=deck[round];
  if(action==='route'){route=b.dataset.route;render(true);return;}
  if(action==='home'){deck=[];route='game';render(true);return;}
  if(action==='resume'){route='game';render(true);return;}
  if(action==='start'){start(b.dataset.level);return;}
  if(action==='pick'){selected[Number(b.dataset.column)]=b.dataset.part;message='';render();return;}
  if(action==='hint'){hinted=true;supported=true;announce('A hint is shown below the activity.');render();return;}
  if(action==='check-build'){
    if(!MorphCore.partsCorrect(selected,m.parts)){supported=true;const wrong=selected.map((p,i)=>p!==m.parts[i]?['prefix','base','suffix'][i]:null).filter(Boolean);message=`Revisit your ${wrong.join(' and ')}. Use the meaning clue and the full base. You can change a tile and check again.`;messageType='error';announce(message);render();return;}
    stage=m.spellings.length?'spell':'meaning';answered=false;chosen=null;hinted=false;message=m.spellings.length?'You found the meaningful parts. Now investigate the finished spelling.':'The parts fit. Now explain how the word works in the sentence.';messageType='success';render(true);return;
  }
  if(action==='answer-spell'){chosen=b.dataset.answer;answered=chosen===m.word;if(!answered)supported=true;message=answered?m.rule:`That spelling does not fit this word sum. ${m.rule} Choose again.`;messageType=answered?'success':'error';announce(message);render();return;}
  if(action==='to-meaning'){stage='meaning';answered=false;chosen=null;message='';hinted=false;render(true);return;}
  if(action==='answer-meaning'){chosen=b.dataset.answer;answered=chosen===m.meanings[0];if(!answered)supported=true;message=answered?`${m.word} means “${m.meanings[0]}” here. The base and the affixes work together.`:`That meaning does not fit this sentence. Read the word sum and think about each part’s job. Try again or use a hint.`;messageType=answered?'success':'error';announce(message);render();return;}
  if(action==='next'){results.push({id:m.id,completed:true,supported});round++;if(round<deck.length)newRound();render(true);return;}
  if(action==='review'){start(level,results.filter(x=>x.supported).map(x=>x.id));return;}
  if(action==='lab-word'){labWord=b.dataset.word;render();return;}
  if(action==='preview'){const word=allWords.find(m=>m.word===b.dataset.word);labBase=word.parts[1];labWord=word.word;route='lab';render(true);return;}
  if(action==='print'){if(route==='game')printLevel=level;printable(b.dataset.key==='true');return;}
});
document.addEventListener('change',event=>{if(event.target.id==='lab-base'){labBase=event.target.value;labWord='';render();}if(event.target.id==='print-level'){printLevel=event.target.value;}});
render();
