const {JSDOM,VirtualConsole}=require('jsdom');const fs=require('fs');const path=require('path');
const root=path.resolve(__dirname,'..');const errors=[];const out=[];
const vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));vc.on('error',e=>errors.push(String(e)));
const dom=new JSDOM(fs.readFileSync(path.join(root,'index.html'),'utf8'),{url:'https://example.invalid/canada-through-time-expanded/',runScripts:'outside-only',pretendToBeVisual:true,virtualConsole:vc});const w=dom.window,d=w.document;
w.matchMedia=()=>({matches:true});w.TextDecoder=TextDecoder;w.TextEncoder=TextEncoder;
w.fetch=async url=>{const f=path.join(root,url);if(!fs.existsSync(f))throw Error('Missing asset '+url);return new Response(fs.readFileSync(f),{status:200});};
w.Image.prototype.decode=async function(){const asset=this.getAttribute('src');if(!fs.existsSync(path.join(root,asset)))throw Error('Missing source image '+asset);};
w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;};
for(const f of ['vendor/fflate.min.js','vendor/d3.min.js','app.js'])w.eval(fs.readFileSync(path.join(root,f),'utf8'));
const delay=ms=>new Promise(r=>setTimeout(r,ms));async function wait(fn,msg){for(let i=0;i<300;i++){if(fn())return;await delay(5);}throw Error(msg+' '+errors.join(';'));}const get=id=>d.getElementById(id);const check=(ok,msg)=>{if(!ok)throw Error(msg);};
async function year(y){const option=[...get('year-select').options].find(o=>o.textContent.startsWith(String(y)+' ·')||y===1500&&o.textContent.startsWith('Before 1600')||y===1840&&o.textContent.startsWith('1840 / 1841'));check(option,'Missing year '+y);get('year-select').value=option.value;get('year-select').dispatchEvent(new w.Event('change',{bubbles:true}));await wait(()=>get('loading').hidden,'Failed year '+y);await delay(10);}
function log(s){out.push('PASS '+s);console.log('PASS '+s);}
(async()=>{await wait(()=>d.documentElement.dataset.ready==='true','Initialization failed');const timeline=JSON.parse(fs.readFileSync(path.join(root,'data/timeline.json')));check(!get('source-map').querySelector('image'),'Before 1600 has colonial map');check(!get('regions').querySelector('path'),'Before 1600 has provincial borders');check(get('geography').querySelectorAll('circle').length===6,'Missing geographic references');get('region-list').querySelector('button').click();check(get('region-details').textContent.includes('ocean')||get('region-details').textContent.length>40,'Geography notes missing');log('Indigenous-homelands context has no colonial colours or provincial boundaries, and geography markers open notes');
for(const e of timeline){await year(e.year);check(get('story-year').textContent===(e.label||String(e.year)),'Wrong label '+e.year);check(get('inquiry-question').textContent===e.grade7,'Missing Grade 7 '+e.year);if(e.early&&!e.context){
check(!get('source-map').querySelector('image'),'Early date still uses a raster '+e.year);
const paths=[...get('regions').querySelectorAll('path')];check(paths.length>4,'Missing early polygons '+e.year);check(paths.every(p=>p.getAttribute('d')&&!p.getAttribute('d').includes('NaN')),'Invalid early geometry '+e.year);
const chip=[...get('region-list').querySelectorAll('button')].find(b=>!b.dataset.region.includes('geographic context')&&!['Hudson Bay','Great Lakes','St. Lawrence River','Rocky Mountains','Atlantic Ocean','Pacific Ocean'].includes(b.dataset.region));check(chip,'No selectable colony '+e.year);chip.click();check(get('region-details').textContent.length>70,'Missing colonial note '+e.year);check(get('map').querySelector(`[aria-label^="${chip.dataset.region}"]`)?.getAttribute('aria-pressed')==='true','Selected polygon is not highlighted '+e.year);
check(get('show-previous').disabled===(e.year===1667),'Incorrect early previous-boundary control '+e.year);check(get('download-year').textContent.includes('GeoJSON'),'No early GeoJSON download '+e.year);
}else if(!e.early){check(get('regions').querySelectorAll('path').length>0,'No vector map '+e.year);check(!get('source-map').querySelector('image'),'Stale raster '+e.year);check(!get('source-map').querySelector('path'),'Stale geographic cover '+e.year);const paths=[...get('regions').querySelectorAll('path')];check(paths.every(p=>!p.getAttribute('d').includes('NaN')),'Invalid geometry '+e.year);}
if(e.year>=1912&&e.year<1999){check(d.querySelector('.nwt-title')?.textContent.includes('Northwest Territories'),'Missing unified NWT '+e.year);check([...get('regions').querySelectorAll('path')].some(p=>p.getAttribute('aria-label').includes('District of Mackenzie')),'Lost district boundaries '+e.year);}if(e.year===1999)check(!d.querySelector('.nwt-title'),'Stale NWT districts label after Nunavut');log('date '+(e.label||e.year));}
await year(1840);check(get('map-note').textContent.includes('1841')&&get('map-note').textContent.includes('1846')&&get('map-heading').textContent.includes('1841'),'1841 qualification missing');check(get('reference-map').textContent.includes('1849'),'Later source reference qualification missing');check(get('event-summary').textContent.includes('1840')&&get('event-summary').textContent.includes('1841'),'Union dates missing');log('Digital Act of Union view distinguishes 1840 law, 1841 union and later 1849 reference');
get('grade-prompt').value='grade4';get('grade-prompt').dispatchEvent(new w.Event('change'));check(get('inquiry-question').textContent===timeline.find(e=>e.year===1840).grade4,'Grade 4 selector broken');log('Grade 4 / Grade 7 inquiry switch');
await year(1867);check(!get('show-previous').disabled,'Early-to-Confederation comparison is disabled');await year(1870);get('show-previous').checked=true;get('show-previous').dispatchEvent(new w.Event('change'));await wait(()=>get('previous-regions').querySelector('path'),'Previous boundaries missing');log('Previous digital boundaries are available across the colonial/Confederation transition');
await year(1713);get('compare-button').click();await wait(()=>get('compare-status').textContent==='Comparison ready.','Compare failed');check(get('compare-map-left').querySelector('svg path')&&get('compare-map-right').querySelector('svg path'),'Early digital comparison missing');check(!get('compare-map-left').querySelector('img')&&!get('compare-map-right').querySelector('img'),'Raster retained in digital comparison');get('close-compare').click();await year(1912);get('compare-button').click();await wait(()=>get('compare-status').textContent==='Comparison ready.','Vector compare failed');check(get('compare-map-left').querySelector('svg path')&&get('compare-map-right').querySelector('svg path'),'Vector comparison missing');get('close-compare').click();log('Early and later maps both use geographic vector comparisons');
await year(1774);get('region-list').querySelector('button').click();get('zoom-in').click();await delay(60);const before={year:get('story-year').textContent,selection:get('region-title').textContent,zoom:get('map-world').getAttribute('transform')};check(!before.zoom.includes('scale(1)'),'Zoom in did not change map');w.innerWidth=390;w.innerHeight=667;w.dispatchEvent(new w.Event('resize'));await delay(60);check(before.year===get('story-year').textContent&&before.selection===get('region-title').textContent&&before.zoom===get('map-world').getAttribute('transform'),'Resize lost work');log('Resize event preserves date, selection and pan/zoom (DOM simulation)');
get('show-labels').checked=false;get('show-labels').dispatchEvent(new w.Event('change'));check(get('region-labels').getAttribute('display')==='none','Labels toggle');get('show-labels').checked=true;get('show-labels').dispatchEvent(new w.Event('change'));get('show-geography').checked=false;get('show-geography').dispatchEvent(new w.Event('change'));check(get('geography').querySelectorAll('circle').length===1&&get('geography').querySelector('circle').getAttribute('aria-label')==='Saint-Pierre and Miquelon','Geography toggle should preserve French island marker');log('Labels and geography controls');
await year(1774);const nativeTimeout=w.setTimeout.bind(w);w.setTimeout=(fn,ms,...args)=>nativeTimeout(fn,ms===2000?50:ms,...args);get('speed').value='2000';get('play').click();await wait(()=>get('story-year').textContent==='1791','Playback did not advance');get('play').click();check(get('play').getAttribute('aria-pressed')==='false','Pause failed');get('map').dispatchEvent(new w.KeyboardEvent('keydown',{key:'ArrowRight',bubbles:true}));await wait(()=>get('story-year').textContent==='1840 / 1841' && get('loading').hidden,'Keyboard advance failed');log('Playback, pause and keyboard date navigation');
await year(1713);get('fit-map').click();await delay(40);check(errors.length===0,'Runtime errors: '+errors.join(';'));log('No application runtime errors across all 30 stops and tested controls');fs.writeFileSync(path.resolve(__dirname,'validation.txt'),out.join('\n')+'\n');dom.window.close();})().catch(e=>{console.error(e);dom.window.close();process.exitCode=1;});
