(()=>{'use strict';
const M=window.TradingPostModel,game=document.querySelector('#game'),KEY='bgsd-trading-post-v1';let state=null,sound=false,audio=null,busy=false,flashTimer;
try{state=M.restore(JSON.parse(localStorage.getItem(KEY)));}catch{}
const boxes=[[1,3,98,95],[100,3,98,95],[200,3,99,95],[299,3,100,95],[4,100,95,99],[100,102,94,94],[190,98,125,101],[316,99,83,100],[0,198,103,100],[100,201,105,95],[207,209,97,83],[305,195,94,103]];
const art=id=>{const i=M.BY_ID[id];return `<svg class="item" viewBox="${boxes[i.cell].join(' ')}" aria-hidden="true" focusable="false"><image href="assets/items.webp" x="0" y="0" width="400" height="300" preserveAspectRatio="none"/></svg>`;};
const entries=counts=>M.ITEMS.filter(i=>counts[i.id]>0),names=counts=>entries(counts).map(i=>`${counts[i.id]} ${i.name.toLowerCase()}${counts[i.id]>1&&i.id!=='silver'&&i.id!=='tools'?'s':''}`).join(', ');
const card=(i,n)=>`<div class="cargo-card">${art(i.id)}<b>×${n}</b><strong>${i.name}</strong><small>${i.points} pts each</small></div>`;
const cards=counts=>entries(counts).map(i=>card(i,counts[i.id])).join('');
const label=()=>state.role==='community'?'Goods for your community':'Furs for Montreal';
const partnerName=()=>state.role==='community'?(state.round===1?'Montreal merchants':'New merchants'):(state.round===1?'River trading party':'Lakeshore trading party');
const postArt=()=>state?.role==='merchant'?'assets/post-community.webp':'assets/post.webp';
function save(){try{if(state)localStorage.setItem(KEY,JSON.stringify(state));else localStorage.removeItem(KEY);}catch{}}
function note(type){if(!sound)return;try{audio??=new (window.AudioContext||window.webkitAudioContext)();audio.resume();const start=audio.currentTime;[type==='dice'?175:440,type==='dice'?220:660].forEach((f,i)=>{const osc=audio.createOscillator(),gain=audio.createGain();osc.frequency.value=f;osc.type=type==='dice'?'triangle':'sine';gain.gain.setValueAtTime(.0001,start+i*.1);gain.gain.exponentialRampToValueAtTime(.08,start+i*.1+.02);gain.gain.exponentialRampToValueAtTime(.0001,start+i*.1+.16);osc.connect(gain);gain.connect(audio.destination);osc.start(start+i*.1);osc.stop(start+i*.1+.18);});}catch{}}
function set(next,focus=false){state=next;save();render();if(focus)game.querySelector('h1,h2')?.focus({preventScroll:true});}
function scene(image,inner,extra=''){return `<section class="scene ${extra}"><img class="painting" src="${image}" alt=""><div class="glimmer"></div><div class="scene-copy">${inner}</div></section>`;}
function title(){return scene('assets/arrival.webp',`<span class="kicker">NEW FRANCE · THE TRADING FAIR</span><h1 tabindex="-1">A good bargain.<br>A story to bring home.</h1><p>Two rounds. Your stock. What will you trade for?</p><div class="choice-row"><button class="role-choice" data-role="community">${art('beaver')}<span><strong>Trading party</strong><small>Trade furs for community goods</small></span><span class="arrow">→</span></button><button class="role-choice" data-role="merchant">${art('blanket')}<span><strong>Travelling merchant</strong><small>Trade goods for valuable furs</small></span><span class="arrow">→</span></button></div>`);}
const pips=[[4],[0,8],[0,4,8],[0,2,6,8],[0,2,4,6,8],[0,2,3,5,6,8]];
function die(face,newest){return `<span class="die ${face?'rolled':'blank'}" role="img" aria-label="${face?'Die showing '+face:'Die not rolled'}">${face?Array.from({length:9},(_,i)=>`<span ${pips[face-1].includes(i)?'class="pip"':''}></span>`).join(''):''}</span>`;}
function stock(){const complete=state.rolls.length===3;return scene('assets/arrival.webp',`<span class="kicker">CHAPTER ONE · YOUR STARTING STOCK</span><h1 tabindex="-1">Roll your cargo.</h1><p>${state.role==='community'?'Gather your furs for the trading fair.':'Gather your goods for the trading fair.'}</p><div class="dice-area" aria-label="Three cargo dice">${[0,1,2].map(n=>die(state.rolls[n],n===state.rolls.length-1)).join('')}</div><div class="starting-stock" aria-live="polite">${cards(state.own)}</div><button class="gold" data-action="${complete?'arrive':'roll'}" ${busy?'disabled':''}>${complete?'Head to the post →':`Roll ${state.rolls.length+1} of 3`}</button>`,'stock-screen');}
function cutscene(){const between=state.phase==='between',home=state.phase==='home';return scene(home?'assets/home.webp':between?postArt():'assets/arrival.webp',`<span class="kicker">${home?'THE FAIR IS OVER':between?'CHAPTER THREE · ROUND TWO':'CHAPTER TWO · ROUND ONE'}</span><h1 tabindex="-1">${home?'Time to bring it home.':between?'One last chance.':'The trading fair begins.'}</h1><p>${home?'Unpack what you received. Discover what your bargains brought back.':between?'New partners. New priorities. Your remaining stock comes with you.':'Your partners are ready. Step inside and make a bargain.'}</p><div class="cut-actions"><button class="gold" data-action="${home?'finish':'enter'}">${home?'Unpack your cargo →':'Enter the trading room →'}</button><button class="skip-scene" data-action="${home?'finish':'enter'}">Skip scene</button></div>`,between?'mood-late':'');}
function shelf(side){const k=side==='give'?M.kind(state.role):M.opposite(state.role),counts=side==='give'?state.own:state.stock;return `<section class="shelf"><h3>${side==='give'?'Your shelf':'Their shelf'}</h3><div class="shelf-grid">${M.list(k).map(i=>{const left=counts[i.id]-state[side][i.id],wanted=side==='give'&&state.wanted.includes(i.id);return `<button class="shelf-item ${wanted?'wanted':''}" data-side="${side}" data-item="${i.id}" data-delta="1" aria-label="${side==='give'?'Offer':'Ask for'} one ${i.name.toLowerCase()}, ${left} available, ${i.points} points each" ${left===0?'disabled':''}>${wanted?'<span class="wanted-star" aria-hidden="true">★</span>':''}<span class="quantity">${left}</span>${art(i.id)}<strong>${i.name}</strong><small>${i.points} pts</small></button>`;}).join('')}</div></section>`;}
function tray(side){return `<div><div class="tray-heading"><strong>${side==='give'?'YOU OFFER':'YOU RECEIVE'}</strong><b>${M.value(state[side])} pts</b></div><div class="tray-items">${entries(state[side]).map(i=>`<button class="table-item" data-side="${side}" data-item="${i.id}" data-delta="-1" aria-label="Remove one ${i.name.toLowerCase()} from ${side==='give'?'your offer':'your request'}">${art(i.id)}<b>×${state[side][i.id]}</b><span class="remove" aria-hidden="true">−</span></button>`).join('')||'<span class="empty-tray">Choose from the shelf</span>'}</div></div>`;}
function mini(counts){return entries(counts).map(i=>`<span class="token" aria-label="${counts[i.id]} ${i.name}">${art(i.id)}<b>×${counts[i.id]}</b></span>`).join('');}
function trading(){const p=state.pending,kind=p?.kind;let reply=kind==='agreement'?'They agree to your offer. Make the exchange?':kind==='counter'?'“Could you make this bargain instead?”':kind==='refusal'?'“That won’t work for us. Try a different offer.”':state.log.length?'Your last bargain is packed. What will you trade next?':'Choose goods from both shelves.';
return `<div class="round-top"><div class="round-badge"><span class="${state.round===1?'current':''}">1</span><span class="${state.round===2?'current':''}">2</span> ROUND ${state.round} OF 2</div><div class="cargo-score">Bring home <strong>${M.score(state)}</strong> pts</div></div><div class="trade-layout"><section class="world" aria-label="The trading counter"><div class="room"><img src="${postArt()}" alt="A painted timber trading room with two trading partners, stocked shelves and a doorway overlooking canoes on the river."><span class="room-label">${state.role==='community'?'THE MERCHANTS’ COUNTER':'THE TRADING PARTIES’ COUNTER'}</span><span class="flame"></span></div><div class="wood"><div class="shelves">${shelf('give')}${shelf('take')}</div><div class="barter-counter" aria-label="Your proposed bargain">${tray('give')}<div class="swap-arrow" aria-hidden="true">⇄</div>${tray('take')}</div><div class="counter-footer"><span>Tap a shelf to add. Tap the counter to remove.</span><button data-action="clear">Clear offer</button></div></div></section><aside class="partner-panel"><span class="kicker">YOUR TRADING PARTNER</span><h2 tabindex="-1">${partnerName()}</h2><div class="wants"><span>Looking for</span><div class="want-items">${state.wanted.map(id=>`<span>${art(id)}<b>${M.BY_ID[id].name}</b></span>`).join('')}</div></div><p class="reply ${kind||''}" role="status">${reply}</p>${['agreement','counter'].includes(kind)?`<div class="proposed"><strong>${kind==='counter'?'Their counteroffer':'Agreed bargain'}</strong><div class="mini-offer">${mini(p.give)}<span>⇄</span>${mini(p.take)}</div><p class="partner-tip">You offer ${M.value(p.give)} pts · receive ${M.value(p.take)} pts</p></div>`:''}<div class="partner-actions">${['agreement','counter'].includes(kind)?'<button class="gold" data-action="accept">Accept & exchange →</button><button data-action="edit">Change the offer</button>':`<button class="gold" data-action="negotiate" ${M.valid(state)?'':'disabled'}>Make an offer →</button><button data-action="hint">Hint</button>`}</div><div class="round-exit"><button data-action="advance">${state.round===1&&M.total(state.own,M.kind(state.role))>0?'Next trading partner →':'Go home →'}</button></div><p class="partner-tip">${state.round===1?'You may save your stock for round two.':'Last round. Untraded starting stock earns 0 points.'}</p><p class="saved-note">${state.log.length} ${state.log.length===1?'exchange':'exchanges'} · progress saved on this device</p></aside></div>`;}
function results(){const received=Object.fromEntries(M.ITEMS.map(i=>[i.id,i.kind===M.opposite(state.role)?state.own[i.id]:0])),left=M.total(state.own,M.kind(state.role)),score=M.score(state);return scene('assets/home.webp',`<span class="kicker">CHAPTER FOUR · ${label().toUpperCase()}</span><h1 tabindex="-1">${score?'Your bargains came home.':'A fair to learn from.'}</h1><div class="score-seal"><b>${score}</b><span>TRADE<br>POINTS</span></div><div class="received-tray" aria-label="Your received goods">${cards(received)||'<p>No exchanges this time. Try making an offer next visit.</p>'}</div><p class="results-note">${state.log.length} exchanges · ${left} untraded starting ${left===1?'item':'items'} scored 0.</p><details class="log"><summary>See your bargains +</summary>${state.log.map(d=>`<p>Round ${d.round}: ${names(d.give)} → ${names(d.take)} · ${M.value(d.take)} pts received</p>`).join('')||'<p>No bargains made.</p>'}<p>Each partner had their own priorities. These points are game scores, not historical prices.</p></details><div class="result-buttons"><button class="gold" data-action="again">Play again →</button><button data-action="other">Try the other side</button></div>`,'results');}
function render(){game.innerHTML=!state?title():state.phase==='stock'?stock():state.phase==='trade'?trading():state.phase==='results'?results():cutscene();document.querySelector('#restart').disabled=!state;}
function showHint(){document.querySelector('#helpDialog').showModal();}
game.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled||busy)return;
if(b.dataset.role){set(M.fresh(b.dataset.role),true);return;}
if(b.dataset.item){const id=b.dataset.item,side=b.dataset.side,delta=Number(b.dataset.delta);set(M.stage(state,side,id,delta));game.querySelector(`[data-side="${side}"][data-item="${id}"][data-delta="${delta}"]`)?.focus({preventScroll:true});return;}
const action=b.dataset.action;if(!state&&action)return;
if(action==='roll'){note('dice');set(M.roll(state));}
if(action==='arrive')set(M.arrive(state),true);
if(action==='enter')set(M.enter(state),true);
if(action==='clear')set(M.clear(state));
if(action==='negotiate')set(M.negotiate(state));
if(action==='edit')set({...state,pending:null});
if(action==='accept'){const old=state,next=M.accept(state);if(next===old)return;note('exchange');set(next);const pop=document.createElement('div');pop.className='exchange-pop';pop.textContent='Bargain made!';pop.setAttribute('aria-hidden','true');document.body.append(pop);clearTimeout(flashTimer);flashTimer=setTimeout(()=>pop.remove(),1250);}
if(action==='hint')showHint();
if(action==='advance')set(M.advance(state),true);
if(action==='finish')set(M.finish(state),true);
if(action==='again')document.querySelector('#restartDialog').showModal();
if(action==='other')set(M.fresh(state.role==='community'?'merchant':'community'),true);
});
document.querySelector('#sound').addEventListener('click',e=>{sound=!sound;e.currentTarget.textContent=sound?'Sound on':'Sound off';e.currentTarget.setAttribute('aria-pressed',String(sound));if(sound)note('exchange');});
document.querySelector('#help').addEventListener('click',showHint);
document.querySelector('#restart').addEventListener('click',()=>document.querySelector('#restartDialog').showModal());
document.querySelector('#confirmRestart').addEventListener('click',()=>{document.querySelector('#restartDialog').close();set(null,true);});
document.querySelector('#teacher').addEventListener('click',()=>document.querySelector('#teacherDialog').showModal());
document.addEventListener('visibilitychange',()=>{if(document.hidden)audio?.suspend();});
window.addEventListener('pagehide',save);
window.TradingPostPreview={getState:()=>state?JSON.parse(JSON.stringify(state)):null};
render();
})();
